### ISSUE TITLE
Release 15.2 proposal

### ISSUE THREAD

**Issue by zabil** [gocd/gocd#1076]
## CI/CD features
 - [ ] #1082 - Elastic agents 
 - [ ] #987  - Artifact cleanup extension
 - [x] #194  - Allow secure variables (environment) on pipeline groups, stages and jobs
 - [x] #142  - Console output with ansi colors

## API enhancements
 - [ ] #775  - API to trigger stage and job 
 - [ ] #878  - Go config edit API - ability to CRUD parts of config [on going - across releases]
 - [ ] #572  - APIs inconsistent: some JSON, some XML, some both (and even some CSV) [on going - across releases]
 - [ ] #52   - Change a pipeline label using the API
 - [x] #1029 - Improve the response of the endpoint SCM endpoint

## Performance fixes
 - [ ] #838  - Fix cruise config xml save performance issues [on going - across releases]
 - [ ] #911  - Move agent configuration out of cruise config 
 - [x] #1034 - Server freezes when put under load
 
## Bug fixes
 - [x] #1039 - Builds not triggered on SVN external changes 
 - [x] #649  - Destination folder inside flyweight gets deleted in case a material is specified twice in the config (with and without destination) 
 - [ ] #756   - multiple copies of job running at the same time 
 - [x] #68     - Rescheduled pipeline does not show the updated Agent IP details on the Job details page. 
 - [x] #1089 - Rescheduled Jobs not being marked as completed on completion
 - [x] #1061 - UTF-8 characters not getting displayed correctly when the job is running or when it is rescheduled 
 - [x] #1060 - Assets (and content) could be served as gzip
 - [x] #1012 - Unable to change configuration after making one of the pipelines use a template

## Technical Debt
 - [ ] #1085 - Migrate from twist tests to [gauge](http://getgauge.io)
 - [ ] #1086 - Support for JDK 8    
 - [ ] #1088 - Add a performance pipeline to build.go.cd 

---

**30th June, 2015: Update**:
> All of the incomplete tasks have been pushed out to the next release gocd/gocd#1104. You may track progress there.
> - Ketan

**Comment by srinivasupadhya** [comment]
There were a few issue marked for [15.2 milestone](https://github.com/gocd/gocd/issues?q=is%3Aopen+is%3Aissue+milestone%3A%22Release+15.2%22).

**Comment by zabil** [comment]
@srinivasupadhya yes, going through them and categorizing it.

**Comment by ciotlosm** [comment]
Hi, 
After going through the list, here are my votes (in priority order):
 #838 - Fix cruise config xml save performance issues
 #878 - Go config edit API - ability to CRUD parts of config
 #1034 - Server freezes when put under load
 #911 - Move agent configuration out of cruise config
 #142 - Console output with ansi colors
 #572 - APIs inconsistent: some JSON, some XML, some both (and even some CSV)

There are two other items I'd be interested in (elastic agents and horizontal scaling of Go server), but I guess those are quite big changes and probably won't make it in 15.2 anyway :)

**Comment by srinivasupadhya** [comment]
[Roadmap](http://www.go.cd/contribute/roadmap.html) needs to be updated. Will do once we have settled on the list.

**Comment by jvale** [comment]
Hi!

In order:
#838 - Fix cruise config xml save performance issues
#911 - Move agent configuration out of cruise config
#878 - Go config edit API - ability to CRUD parts of config
#572 - APIs inconsistent: some JSON, some XML, some both (and even some CSV)
#775 - API to trigger stage and job

**Comment by arvindsv** [comment]
> There are two other items I'd be interested in (elastic agents and horizontal scaling of Go server), but I guess those are quite big changes and probably won't make it in 15.2 anyway :)

Actually, I think 15.2 should be about elastic agents and ridiculously quick config save. The others should happen as time permits, and some of them should be contributions from members of the community. Why I say that is because some parts of the core (especially for big features like the one I mentioned)  are harder to change for someone with a little context. Console log coloring requires only a little context, where as config save performance requires a lot. I think the core team should handle the hard parts, before getting to the easy ones.

**Comment by zabil** [comment]
@arvindsv shall i create an issue place holder for elastic agents and add it to the list? Couldn't find it earlier.

**Comment by arvindsv** [comment]
> shall i create an issue place holder for elastic agents and add it to the list? Couldn't find it earlier.

@zabil: Sure. If you can mention [this RFC](https://arvindsv.github.io/elastic_agents_for_gocd.html) in the description, that would be great. Thanks!

**Comment by gorganc** [comment]
Hi,

My preferences: 
#838 - Fix cruise config xml save performance issues
#987 - Artifact cleanup extension

Thanks,
Claudiu

**Comment by psoftadi** [comment]
Hi!

In order:

#838 - Fix cruise config xml save performance issues
#911 - Move agent configuration out of cruise config
#775 - API to trigger stage and job

**Comment by campeanc** [comment]
Hi,

My preferences:

#838 - Fix cruise config xml save performance issues
#911 - Move agent configuration out of cruise config
#878 - Go config edit API - ability to CRUD parts of config
#142 - Console output with ansi colors
#775 - API to trigger stage and job

Thanks,
Cristi

**Comment by alivespirit** [comment]
Hi,
From my point of view these issues would be good:

#838 - Fix cruise config xml save performance issues
#1034 - Server freezes when put under load
#911 - Move agent configuration out of cruise config

Regards,
Roman

**Comment by PohoL** [comment]
Hi,

This are my options:
#838  - Fix cruise config xml save performance issues
#911  - Artifact cleanup extension
#775  - API to trigger stage and job

Thanks,
Lucian

**Comment by ghitalazar** [comment]
Hi,
following my options:

 #838 - Fix cruise config xml save performance issues
 #911 - Move agent configuration out of cruise config
 #775 - API to trigger stage and job
 #911 - Artifact cleanup extension

Regard,
Ghita

**Comment by michaelmaley** [comment]
Hi, My choices are:

#194 - Allow secure variables (environment) on pipeline groups, stages and jobs 
#1034 - Server freezes when put under load
#234 - Upgrade to TFS SDK 12.0.1
#878 - Go config edit API - ability to CRUD parts of config

Thanks,
Michael

**Comment by heathsnow** [comment]
These would be incredible:

#194 - Allow secure variables (environment) on pipeline groups, stages and jobs
#52 - Change a pipeline label using the API

**Comment by jasonduff** [comment]
***** More important than most of these to us is the ability to template stages and/or jobs.  This would give us the ability to cut our # of pipelines down drastically and still maintain consistency with the reuse provided by templating.  Most other CD products have this feature.

My votes for what was listed above:
 #987 - Artifact cleanup extension
 #1029 - Improve the response of the endpoint SCM endpoint
 #775 - API to trigger stage and job
 #878 - Go config edit API - ability to CRUD parts of config
 #572 - APIs inconsistent: some JSON, some XML, some both (and even some CSV)
 #978 - SCM extension point - Provide ability to specify default values for fields and save it in config.xml
 #838 - Fix cruise config xml save performance issues
 #1012 - Unable to change configuration after making one of the pipelines use a template

**Comment by reidca** [comment]
My votes (in order) are:

 #1082 - Elastic agents
 #987 - Artifact cleanup extension
 #194 - Allow secure variables (environment) on pipeline groups, stages and jobs
 #911 - Move agent configuration out of cruise config

**Comment by sweitzel74** [comment]
Voting:
#194 - Allow secure variables (environment) on pipeline groups, stages and jobs
#52 - Change a pipeline label using the API
#1082 - Elastic agents

**Comment by lruth-daptiv** [comment]
My votes:

#142 - Console output with ansi colors
#194 - Allow secure variables (environment) on pipeline groups, stages and jobs
#52 - Change a pipeline label using the API
#1082 - Elastic agents
#775 - API to trigger stage and job

**Comment by thenathanjones** [comment]
#1039 - Go is basically useless for me until I can sort this one out
#1092 - This will be a definite improvement for me fighting against using TeamCity
 #68 - This will be a definite improvement for me fighting against using TeamCity
 #1089 - This will be a definite improvement for me fighting against using TeamCity

**Comment by thenathanjones** [comment]
@zabil this may be a dumb question but I'll ask it anyway. If we're eating our own dogfood and at least leaning towards doing CD, should be not be making a release every time we're comfortable with the current state of the build? I suppose in short what I'm asking, why do we need such planned and large sets of features for a release rather than a prioritised list we work through?

**Comment by arvindsv** [comment]
Not a dumb question at all. I'm sure @zabil or others will answer. So, won't say much. But, to me, this is more about what people are interested in (and so, priority in a sense). The releases are going to become much shorter soon (and not really  tied to big features). Every build already gets uploaded to go.cd/download right now (for instance, the one with your SVN externals fix is already up there - build 15.1.0-1875). However, it gets marked as experimental. One aspect that is missing in the whole pipeline is performance tests, which are internal as of now. There's work being done towards moving that to build.go.cd. Once that is done, we can try playing around with removing the "experimental" label.

**Comment by thenathanjones** [comment]
Oh for sure, I understand needing to know what people are interested in. I just saw the culled list of things that are still in the current release and thought it was still really big! To me, even if only a couple of those were implemented that'd be super useful.

In a related question, is there any possibility that experimental builds could be put in the RPM/DEB repositories? I've got Chef scripts I'm using to install Go, but they don't work for both the experimental builds and the supported ones.

**Comment by arvindsv** [comment]
> Is there any possibility that experimental builds could be put in the RPM/DEB repositories

Let's take that conversation away from here, if you don't mind. I've been thinking about it and have some ideas (cannot use bintray). Can you start a mailing list thread about it or a different GitHub issue?

**Comment by thenathanjones** [comment]
Done. #1102

2015-05-06 11:09 GMT+12:00 Aravind SV <notifications@github.com>:

**Comment by ketan** [comment]
> why do we need such planned and large sets of features for a release rather than a prioritised list we work through?

@thenathanjones - we started out with a "release plan" for 15.2 and ended up adding more and more things. The end result is that this list looks like another release that'd take us several months to get there.

As of a couple of days ago, in the spirit of delivering value continuously - We'd be striving to ship individual features as and when we're ready. So expect 15.2 with less items than what the list here contains, but you'd see it a lot sooner than the several months timeframes of the items listed here. @zabil will soon send that 15.2 list across.

Does that answer your question?

**Comment by thenathanjones** [comment]
Sure does. Thanks for the explanation!

**Comment by zabil** [comment]
@thenathanjones pretty much of what @arvindsv and @ketan already mentioned.  

We also want our users to try out experimental releases, give us feedback on features and iterate before calling it final. 

The list indicates what's priority for users and gives a sense to contributors. Right now, yes we are laying the groundwork for releases once a feature is complete. Expect 15.2 to have many releases :-)

**Comment by ivanmoore** [comment]
Is the release plan for 15.2 decided now?
If not - then I've got only one request:

#1125

**Comment by time4tea** [comment]
#1125 would get my vote too. 

We spend so much time trying to reduce build times, by making the builds faster, optimising networks, proxies, local repos, by making nice tests that don't sleep, by curating the coverage to not repeatedly test the same thing, etc etc, it seems like such a shame that the inter-stage delay is 3x our desired build time!

**Comment by zabil** [comment]
We'll be releasing 15.2 with the items marked as completed here (plus some extra bug fixes and features) soon.

As we are moving shorter releases and will continue working on the in-completed items here #1104
