### ISSUE TITLE
Upgrade to Webpack 5

### ISSUE THREAD

**Issue by chadlwilson** [gocd/gocd#10852]
##### Summary

Currently we are using Webpack 4. Many plugins/loaders etc have changed and are no longer getting patched/updated, so we probably need to migrate to Webpack 5.

Keeping track of work/research here, for want of a better place.

**Things to do**

_General research_
- [x] https://webpack.js.org/migrate/5/
- [x] Research whether the below loaders/plugin combinations are still the best/recommended approaches here

_Plugins/Loaders_
- [x] Upgrade `css-loader` from 5.x to 6+
  - https://github.com/webpack-contrib/css-loader/blob/master/CHANGELOG.md#600-2021-07-14
  - Unclear if 5.x works on webpack 5?  (probably)
- [x] Upgrade `style-loader` from 2.x to 3+
  - https://github.com/webpack-contrib/style-loader/blob/master/CHANGELOG.md#300-2021-06-24
  - Unclear if 5.x works on webpack 5?  (probably)
- Consider switching `file-loader` & `url-loader` to https://webpack.js.org/guides/asset-modules/  
- [x] Upgrade webpack-build-notifier from 2.x to 3+

_Current version already supports webpack 5 / can be deferred_
- [x] Upgrade `ts-loader` from 8.x to 9+
  - https://github.com/TypeStrong/ts-loader/blob/main/CHANGELOG.md#v900
- [x] Upgrade `sass-loader` from 10.x to 13+
  - https://github.com/webpack-contrib/sass-loader/blob/master/CHANGELOG.md#1100-2021-02-05
- [x] Upgrade `stylelint-webpack-plugin` from 2.x to 3+
  - https://github.com/webpack-contrib/stylelint-webpack-plugin/blob/master/CHANGELOG.md#300-2021-07-19 
  - [ ] Also upgrade stylelint to 16+ which is blocked on this
  - [ ] Also upgrade stylelint-config-standard-scss to 12+ which is blocked on this
- [x] Upgrade `fork-ts-checker-webpack-plugin` from 6.x to 7+
  - https://github.com/TypeStrong/fork-ts-checker-webpack-plugin/releases/tag/v7.0.0 
- [x] Upgrade `html-webpack-plugin` from 4.x to 5.x
  - https://github.com/jantimon/html-webpack-plugin/blob/main/CHANGELOG.md#500-2021-02-03
- [x] Upgrade `mini-css-extract-plugin` (and types) from 1.x to 2+
  - https://github.com/webpack-contrib/mini-css-extract-plugin/blob/master/CHANGELOG.md#200-2021-06-30
- [x] Upgrade `estlint-webpack-plugin` from 2.x to 3+
  - https://github.com/webpack-contrib/eslint-webpack-plugin/blob/master/CHANGELOG.md#300-2021-07-19
- [ ] Upgrade `chart.js` to v4+
  - v4 requires webpack 5 in order to be webpakced without babel-loader/preset-env transpilation of dependencies: https://github.com/chartjs/Chart.js/issues/10918
