### ISSUE TITLE
Next Release 15.3+

### ISSUE THREAD

**Issue by jyotisingh** [gocd/gocd#1390]
* [ ] #987  - Artifact cleanup extension (carry over from 15.2)
* [ ] #976  - SCM end-point - plugins needs to show up in new pipeline wizard 
* [ ] #1078  - SCM end-point - ability to select existing scm for a pipeline
* [ ] #978  - SCM end-point - ability to specify default values for fields and save it in config.xml 
* [ ] #866  - JSON validation of request and response made to and by the plugins 
* [ ] #752 - Extend plugin API to enable automatic artifact attachments. 
* [ ] #1246 - Implement a consistent authentication scheme for accessing API's
