### ISSUE TITLE
[PipelineConfig] Materials

### ISSUE THREAD

**Issue by maheshp** [gocd/gocd#1724]
Acceptance Criteria
- [x] List existing materials
- [ ] Add different types of material
  - [x]  TFS
    - [x] Test Connection #1493
  - [x] Git
    - [x] Test Connection
    - [x] Set default branch to master
    - [x] Support shallow clone
  - [x]  Svn
    - [x] Test Connection
  - [x]  Mercurial
    - [x] Test Connection
  - [x]  Perforce
    - [ ] Make view field to multiline.
    - [x] Test Connection
  - [x]  Pipeline
    - [ ] Visualise pipeline dependency #1494 : Part of Fetch Artifact task
  - [ ] Package
    - [ ] Create API end point for Package Material #1507
  - [x] PluggableSCM
    - [x] Create API end point for Pluggable SCM Material #1508
    - [x] Build view to support Pluggable SCm #2488
- [x] Delete Material
- [ ] Validation and error messages
  - [x] Validate branch (#1734)
- [x] UX and UI
- [ ] Tool tip for ignore pattern
- [x] Whitelist of SCM materials refer https://github.com/gocd/gocd/pull/2144

**Comment by zabil** [comment]
For test connection check if #1734 is still an issue

**Comment by juhijariwala** [comment]
#1734 is still an issue.

**Comment by arvindsv** [comment]
Closing. Will have to open new issues for a rewrite.
