### ISSUE TITLE
Basic tooling to gather information needed to resolve support tickets

### ISSUE THREAD

**Issue by GaneshSPatil** [gocd/gocd#2285]
##### Issue Type
- Feature proposal
##### Summary

To be able to effectively help users with support, we usually begin by asking for `/go/api/support`, turning on/off various flags, log levels and gradually and move onto getting hardware specs monitoring etc.

Most of these steps are manual, are error prone and it would be nice if users were able to run some quick commands/tools to be able to help with some of these tasks.

To that effect, we feel that the following is a reasonable start —
- [x] #2280 change in log4j need not require restart.
- [ ] #2282 Turn on web request logging by default for a while even if the performance is affected
- [ ] Command line tool to capture the thread dumps a few seconds apart daily so that we have the thread dump even if server is unresponsive
- [x] Tool to continuously monitor the system running the GoCD server
- [x] #2140, #2283  Render the `/go/api/support` output in JSON
- [ ] Tool to analyze thread dumps, go-server logs, go-agent logs collected so that we can look patterns? Example: looking for blocked threads in all the thread dumps collected

**Comment by lenucksi** [comment]
👍

**Comment by wcurrie** [comment]
Might be worth including some more data from the JDK [ThreadInfo](https://docs.oracle.com/javase/7/docs/api/java/lang/management/ThreadInfo.html) in the /go/api/support output (ie [ThreadInformationProvider](https://github.com/gocd/gocd/blob/master/server/src/com/thoughtworks/go/server/service/support/ThreadInformationProvider.java)):

- getBlockedTime()
- getWaitedTime()
- getLockName()
- getLockOwnerId()

Might have helped with #2082.

If periodic collection is on the cards perhaps allowing go to push metrics to datadog might be considered? Coursera have some code to [push metrics](https://github.com/coursera/metrics-datadog) given an API key. Collection is ~$15/server/month. Free if you only want 1 day of data. Might be getting carried away.

**Comment by GaneshSPatil** [comment]
@wcurrie — merged #2291 based on your feature request.

**Comment by lenucksi** [comment]
@wcurrie Maybe it would be another way to expose the mentioned data sources as plugin endpoints for third parties to make their own plugins to push metrics to monitoring systems of their choice. 
Aside from that: Very nice! 👍

**Comment by GaneshSPatil** [comment]
We haven't seen any more performance issues related to GoCD. 
Though if required, we can build more tools to analyze, monitor and rectify performance issues.

Closing this issue. If required, will create a separate issue for each tool.
