### ISSUE TITLE
Artifact extension to upload and fetch artifact on external repository

### ISSUE THREAD

**Issue by bdpiparva** [gocd/gocd#4049]
##### Issue Type
- Feature proposal

##### Summary

- [x] Configuration to support pluggable artifact(https://github.com/gocd/gocd/issues/4050)
- [x] Publish a artifact to an external store(https://github.com/gocd/gocd/issues/4051)
- [x] Fetch artifact using artifact plugin (https://github.com/gocd/gocd/issues/4053)
- [x] Config repo support for publish and fetch pluggable artifacts
- [x] Add a feature toggle for config views
- [x] Artifact plugins capabilities(https://github.com/gocd/gocd/issues/4052)
- [x] Do not purge content of pluggable artifact metadata from GoCD (https://github.com/gocd/gocd/pull/4218) 
- [x] Show the progress of fetch or publish artifact on the console(https://github.com/gocd/gocd/pull/4208)
- [x] Have same tag to represent pluggable artifact and builtin artifact(https://github.com/gocd/gocd/pull/4278)
- [x] XSL transform to convert `<pluggableArtifact>` to `<artifact type="external">` (https://github.com/gocd/gocd/issues/4604) PR - https://github.com/gocd/gocd/pull/4605
- [x] Have same xml tag to represent different types of fetch tasks. (https://github.com/gocd/gocd/issues/4577) 
- [x] Have configuration subtag on external artifacts (https://github.com/gocd/gocd/issues/4627)
- [ ] ~~Add pluginId attribute to pluggableArtifact and fetchPluggableArtifact elements (https://github.com/gocd/gocd/issues/4206)~~
- [x] Artifact Store Config API(https://github.com/gocd/gocd/pull/4195)
- [x] Artifact Store SPA (https://github.com/gocd/gocd/issues/4580) PR (https://github.com/gocd/gocd/pull/4628)
- [x] Console log rendering bug for fetch artifact  (https://github.com/gocd/gocd/issues/4736)
- [x] Ensure encrypted values for publish external artifact config (#4760)
- [x] Ensure encrypted values for fetch external artifact config (#4760)
- [x] Pipeline Config API support for publish and fetch pluggable artifacts
   - [x] Move Pipeline config API to spark
   - [x] Add support for publish and fetch config of artifact type external (#4760)
- [x] Template Config API support for publish and fetch pluggable artifacts (#4804)
   - [x] Move Template config API to spark
   - [x] Add support for publish and fetch config of artifact type external
- [x] View for publishing pluggable artifact config - normal edit (#4752)
- [x] View for fetch pluggable artifact config - normal edit (#4767)
- [x] Ensure encrypted of external artifact configs from full config save flows (#4875)
- [x] Rename of origin attribute to artifactOrigin on fetch artifact. (#4899 )
- [x] Fix view for template config read only views (#4903)
- [x] Handle deserialization of JsonNull (#4904)
- [x] Select the first plugin in the dropdown to avoid additional interactions. (#4921)
- [x] YAML plugin PR to support
- [x] Documentation for pipeline config API v6
- [x] Documentation for template config API v4
- [x] Documentation for artifact store API v1
- [x] Documentation of artifact extension in plugin-api.gocd.org
- [x] Json and Yaml plugin readme
- [x] Getting started documentation in docs.gocd.org
- [x] Update template API - validate fetch and publish config in the context of the associated pipelines. (#4886)
- [x] Config repos - handle parsing fetch external artifacts. Got broken after rename.
- [x] Config Repos - add migration from target version 2 to 3
- [x] Fix pipeline config API v5 breaking when external artifacts are configured. (#4608)
- [x] Docker registry artifact plugin - support env vars and build file methods to pass the image and tag info during publish artifact. (#4716)
- [x] Move the docker-artifact plugin repository to gocd organization
- [x] Allow for parameterizing artifact id in publish config (#4876)
- [x] Setup CI for the docker artifact plugin similar to https://build.gocd.org/go/admin/templates/bundled-plugins-build/stages/build/job/build/tasks and https://build.gocd.org/go/admin/pipelines/gocd-ldap-authentication-plugin-github-release/edit
- [ ] **Add docker registry artifact plugin to the GoCD helm chart**

#### Out of Scope for Announcement of v1 of artifact extension
- [ ] Test connection  to external artifact Store - Additional request made to the plugin
- [ ] Quick edit page should support publish pluggable artifact config
- [ ] Quick edit page should support fetch pluggable artifact config
- [ ] Artifacts API to provide more info about pluggable artifacts (#4755)
- [ ] GCR and ECR authentication support (https://github.com/gocd/docker-registry-artifact-plugin/issues/9)
- [ ] Fetch artifact configuration for docker plugin (https://github.com/gocd/docker-registry-artifact-plugin/issues/10)

**Comment by varshavaradarajan** [comment]
@rajiesh , @bdpiparva  - this can be closed now, I guess.
