### ISSUE TITLE
Dashboard SPA

### ISSUE THREAD

**Issue by GaneshSPatil** [gocd/gocd#4081]
### Pipelines Dashboard Header
- [x] Implement Pipeline Search (#4111 )
- [ ] Implement Pipeline Selection (Personalize View)
  - [x] Internal API (#4235) (#4312)
  - [ ] Dropdown on dashboard (#4252)
  - [ ] SPA for managing personalizations (#4236)

### Pipelines Groups
- [x] Show Pipeline Groups Depending on the permissions

### Pipeline
- [ ] Dashboard tile (#4254)
- [ ] ~~~Show Current Pipeline Status (Passed: LAST_STAGE, Building: CURRENT_STAGE)~~~
- [ ] ~~~Show previous stage run status when the stage is currently running.~~~
- [x] Errors and Warnings
  - [x] Frontend (#4232) (#4265)
  - [x] API (#4231) (#4256)
- [x] Implement Pause a pipeline
  - [x] API (#4076) (#4188)
  - [x] Frontend (#4254)
- [x] Implement Unpause a pipeline 
  - [x] API (#4076) (#4188)
  - [x] Frontend (#4254)
- [x] Implement Pipeline unlock feature.
  - [x] API (#4237) (#4243)
  - [x] Frontend (#4254)
- [x] Implement Trigger a pipeline
- [x] For Trigger with options
  - [x] API to perform the trigger (replacement for https://api.gocd.org/current/#scheduling-pipelines) (#4346) (#4319)
- [x] For Trigger with options, show options for trigger
  - [x] API (#4233) (#4276) (#4314)
    - [x] Materials
    - [x] Environment Variables
    - [x] Secure Environment Variables
  - [x] Frontend (#4234)
    - [x] Materials (#4320)
    - [x] Environment Variables (#4328)
    - [x] Secure Environment Variables (#4328)
- [x] Material Search
  - [x] API  (#4270) (#4284)
  - [x] Frontend  (#4271)

### Icons
- [ ]  Pipeline Group
- [ ] Pipeline
- [ ] Pipeline Settings
- [ ] Compare
- [ ] Changes Dropdown
- [ ] Stage Status
    - [ ] Failed
    - [ ] Passed
    - [ ] Running
- [ ] Failed icon in the status when the previous run of the stage has failed and current run is in 
progress.

### Buttons
- [x] Trigger
- [x] Trigger with options
- [x] Pause
- [x] Unpause

**Comment by GaneshSPatil** [comment]
* Technical debt:
    - [ ] Restructure Pipeline Groups to include pipelines information.
        - Currently, view deals with two different models while rendering the pipeline group. View iterates over each pipeline name and asks for the pipelines model to give us the details about the pipeline. The pipeline group model can store pipeline information instead of storing pipeline name.
    - [ ] Remove field getters/setters from the model as the model will never update.

**Comment by arvindsv** [comment]
Here are a few small issues/possible improvements I came across:

1. On hover of times in dashboard, it should show relative time.
2. Changes popup doesn't go away if you click outside.
3. In "Errors and Warnings" modal, it doesn't convert HTML properly. See:

    #### Old:
    <img width="748" alt="2018_02_01_11-03-28" src="https://user-images.githubusercontent.com/172235/35688639-9c4d91d6-073f-11e8-98e5-853f04f0b5ca.png">

    #### New:
    <img width="1145" alt="2018_02_01_11-03-10" src="https://user-images.githubusercontent.com/172235/35688667-acca1c46-073f-11e8-9945-7ee77eaf4446.png">

**Comment by arvindsv** [comment]
One last thing: @naveenbhaskar @GaneshSPatil 

The pipeline group header is not very obvious. How about replacing it with:

Pipeline group: group_name  <gear-icon>

That way, it says: "Pipeline group" and now, since there is a gear icon for edit, the pipeline group name can be a link which changes the URL to "dashboard#group-name" and can be filtered by group.

Worth thinking about. Need not be done as a part of the current work.

**Comment by rajiesh** [comment]
@GaneshSPatil - Can we have support for query parameter `autoRefresh` in dashboard URL. This parameter will be used by UI tests which turns off autoRefresh to have better control on the stage status changes and avoid test flakiness due to timing issues

**Comment by ketan** [comment]
> @GaneshSPatil - Can we have support for query parameter autoRefresh in dashboard URL. This parameter will be used by UI tests which turns off autoRefresh to have better control on the stage status changes and avoid test flakiness due to timing issues

I think that's doable, just one question through, we can make this param work on all SPAs to turn off all polling, is that OK? I'd rather not deal with this on a case-by case basis.

**Comment by rajiesh** [comment]
@ketan - Sure, fine with the param available for all SPAs

**Comment by arvindsv** [comment]
@GaneshSPatil Can this be closed? Given all the other work around dashboard, etc?

**Comment by GaneshSPatil** [comment]
Yes. Closing it. Thanks.
