### ISSUE TITLE
Elastic Agent Extention V2 Changelog

### ISSUE THREAD

**Issue by GaneshSPatil** [gocd/gocd#4163]
##### This is the placeholder issue which describes all the elastic agent V2 extension endpoint changes:

- [ ] plugin status report (#3658)
- [ ] plugin capabilities (#3766)
- [ ] Pass along job identifier as part of `create-agent` and `should-assign-work` requests (#4094)
- [ ] `elastic-agent-status-report` page(#4162)
