### ISSUE TITLE
GoCD Usage Data Sharing

### ISSUE THREAD

**Issue by GaneshSPatil** [gocd/gocd#4897]
##### Issue Type

- Feature proposal

##### Summary

Gather some useful metrics which can help improve GoCD, especially its performance but other aspects as well.

PlaceHolder Issue for Data Sharing

- [x] Usage Data APIs
	- [x] Get Usage Data of server (Plain Text) (#4843)
	- [x] Get Usage Data of server (Encrypted) (#4870)

- [x] Usage Reporting API
	- [x] Get Usage Reporting Information (#4843)
	- [x] Start Usage Reporting to Remote server(#4847)
	- [x] Complete Usage Reporting to Remote server(#4847)

- [x] Data Sharing Settings API
	- [x] Get Data Sharing Settings Information(#4843)
	- [x] Toggle Data Sharing Consent(#4843)

- [x] Data Sharing Settings SPA
	- [x] Data Sharing Settings SPA(#4821)

- [x] Data Sharing Notification
	- [x] Show Data Sharing Notification to the Users (#4879)

- [x] Report data to remote data sharing url (#4847)

- [x] Implement Remote Server
	- [x] Implement a backend remote data sharing server to accept the usage data. (Possibly using AWS lambdas)

- [x] Add ServerId Information to the update check

**Comment by rajiesh** [comment]
Moving Update check also to aws lambda was part of this story. However since its not directly related to Data sharing moving it into another story and closing this story
