### ISSUE TITLE
Personalization View Issues Placeholder [pending for discussion]

### ISSUE THREAD

**Issue by adityasood** [gocd/gocd#5021]
The following is a list of issues to be discussed around personalization view story

**Required for 18.8**

- [x] Etag cache seems broken (fixed as part of https://github.com/gocd/gocd/commit/54bc274f9aad3d235f9b0d218b5d1c5321c700c8)

- [x] Adding a new pipeline via config repo does not show the pipeline in the pipeline selection dialog. Had to restart the server to work-around the problem. Added by @ketan. Does not seem consistently reproducible. Please refer to https://github.com/gocd/gocd/issues/5044

- [x] Fix lag when the views are loaded. Currently, when the user switches between different views there is a lag before the pipelines are updated. Should be fixed as part of https://github.com/gocd/gocd/pull/5026

- [x] Pipeline Selection in the "Create New View" widget of personalization view  does not work in safari browser. Fixed as part of https://github.com/gocd/gocd/pull/5036

- [x] Tabs dropdown breaks (goes out of view) when no pipelines are present. @akshaydewan is working on this. PR #5043 Issue https://github.com/gocd/gocd/issues/5047

- [x] Need clarification on the working of "Building" and "Failed" filters. Should they apply to the selected pipelines? If so, do we need to validate that at least one pipeline is selected? Issue https://github.com/gocd/gocd/issues/5049

- [x] Default tab can be renamed and deleted. Prevent deletion only if there is 1 remaining tab. Fixed as part of #5053 (whenever it gets merged, anyway)

~~- [ ]  Disabling addition of personalization tabs for guest users. @akshaydewan working on this.~~

- [x] Minor UI issue: Select Tab > Edit > (Modal opens) > Scroll to bottom and continue scrolling. It should not affect the page behind the modal (PR #5073 )

- [x] Edit Modal: If a single pipeline is selected in a collapsed pipeline group, the main group is unselected. We should have three states for the group checkbox: All Selected, None Selected and Partially Selected. (PR #5077)

- [x] Edit a Tab > Change the name > Save > Saving indicator doesn't go away. (Checked on build.gocd.org on Firefox). Fixed in d2a831fcb3cb3515e38c97b209387a7838f6070b and verified on FF & Chrome.

- [x] User data filter is invalid when user tries multiple saves on personalization view tabs. Issue https://github.com/gocd/gocd/issues/5048, Fix https://github.com/gocd/gocd/pull/5051

- [x] Accessibility Labels PR #5046 and  #5091

- [x] The pipelines with status as "failing" should show up if the pipeline is selected with "building" filter: Issue [#5074]

- [x] The pipelines with no history should not show up when a view is created with "failed/building" filters: Issue [#5075]

**Required Post 18.8.0**

- [ ] Search should be local to a tab. When a switching tab, the search should be cleared. When switching the group-by (`pipeline group` or `environment`), the search should be cleared.

- [x]  Is it necessary to have the first pipeline group expanded in the "Create New View" widget? In context with larger number pipelines in the first group, this becomes an un-necessary scroll. Can we do without it? The expand/collapse button on the group name indicates it's an expandable component.

- [x]  The need for all groups to be selected by default in "Create New View" widget? We have the filters to select "All" or "Newly Created Pipelines". With personalization view, the user gets the ability to maintain multiple tabs of groups of pipelines. This should ideally be some small and logical groups. As a user, it's easier to select whats needed than to select "None" and then select what groups/pipelines are needed. This was helpful when there was just one view, can we move away from it?

- [x]  Do we need the save/revert pop-up when there is just one personalization view tab (default-view) and the user drags it? Fixed in 854decf5c888a4404613402db5704ec5608bec49

- [x] Verify performance impact on Dashboard after JRuby upgrade

- [ ] "Pipelines not in any Environment" tag is a link, as other pipeline group tags, which redirect to pipeline groups.  Since there is no redirection for this tag, this can be text. Also can we think of a better tag for this? 

- [ ] The Drag symbol should be hidden if there's only one view

- [ ] The dropdown for switching views does not close if the tab is in the visible area (but it closes when there is a scroll needed to reach the tab)

- [ ] The user should be able to search for a pipeline-group in the "Create View" modal

**Comment by rajiesh** [comment]
@maheshp @akshaydewan Regarding the issue of config repo pipeline changes not showing up on the pipeline selection modal have created a separate issue https://github.com/gocd/gocd/issues/5044

Issue is reproducible, however to get the pipeline selection modal to show up changes page reload is enough server restart is not needed

**Comment by ketan** [comment]
> Issue is reproducible, however to get the pipeline selection modal to show up changes page reload is enough server restart is not needed

You are absolutely right — it seems that an ajax call for pipeline list is made at page load, and not when the modal is loaded.

**Comment by GaneshSPatil** [comment]
@akshaydewan @marques-work @ketan @arvindsv @adityasood  -- IIRC, we said that we'll call the `personalize view`, just `view`. Though, the validation message says [`Filter`](https://github.com/gocd/gocd/blob/master/server/webapp/WEB-INF/rails.new/webpack/views/dashboard/models/filter_validations.js#L23-L25). 
Should we change it to say `view` as part of this release?
I am OK with the `models, file_names` naming it `filter` in the codebase, only the UI part needs to be changed.

**Comment by adityasood** [comment]
@akshaydewan @maheshp can we look at this list and see if we want to pick up anything anytime soon?

**Comment by adityasood** [comment]
Closing this issue, pending items to be tracked in https://github.com/gocd/gocd/issues/5323
