### ISSUE TITLE
Epic: Thoughts about improving pipelines as code (config-repo)

### ISSUE THREAD

**Issue by arvindsv** [gocd/gocd#5175]
This is a "hub-issue" for thoughts about upcoming improvements to GoCD's pipelines as code feature. Based on a conversation with @kierarad @ibnc @marques-work and @ankitsri11.

### Documentation and getting started experience:
- [Docs are not clear](https://docs.gocd.org/current/advanced_usage/pipelines_as_code.html) about the fact that plugins are bundled.
- Docs suggest editing the XML. There are APIs to add a config repo.
- Confusion between terms: Config repo (which is also something else in GoCD) and "Pipelines as Code".
- Plugins page doesn’t say that the plugins are bundled.

### User experience:
- Feedback loop: Cryptic error messages
- Feedback loop: Error messages are hidden in the “Errors and Warnings” modal. Not obvious.
- Feedback loop: Unclear whether GoCD has seen the commit.
- Feedback loop: Cannot force GoCD to do a check.
- Feedback loop: Cannot see which repo a pipeline came from.
- Information about "How to add it, how to manage it, etc" is not in GoCD
- Can't see YAML / JSON pipelines in GoCD.
- JSON: Was very verbose. It should be: "I want to set this one property and it should work. Instead, had to set a bunch of things to empty array"

## Ideas (for changes to the current state):

There are just ideas. No guarantee that all of these will be done:

- Idea 1: Put in an interface in front of it (SPA) [**Starting with this idea: See #5177**]
    - Should show all configured config repos
    - Who can see this? See “Better authorization” below.
    - Should show the last commit seen and whether there are errors currently (and if so, those errors).
    - Should allow forcing a check on the repo
    - All of this will be through a set of new API endpoints
- Idea 2: Show it under "Create pipelines" as an option.
- Idea 3: Convert existing pipelines to YAML / JSON ("Export as"). [#5338]
- Idea 4: Helper tool which …
    - … assists in building yaml / json templates.
    - … does syntax checking
- Idea 5: External API which checks the code, preflight, before commit.
- Idea 6: Improve those error messages
- Idea 7: Once this is in a good state, change the ["Getting Started" docs](https://www.gocd.org/getting-started/part-1/) to use this.

### Beyond the user experience:

- Encrypted variables: Secrets management. Ties into better secrets management in GoCD.
    - Secrets defined at a higher level (GoCD’s top-level) and ties into the “Better authorization” below.
    - At config repo level, admin should be able to decide which set of keys are usable by this repo.
- All entities from repo?
    - Why should it be restricted to only pipelines?
    - Why not global SCM materials? Like GitHub PR materials.
    - Why not templates? [There's a completely different idea about templates [here](https://github.com/tomzo/gocd-yaml-config-plugin/issues/2)]
- Better authorization
    - Currently, giving access to a config repo’s backing SCM repo means giving full access to the GoCD instance, almost. Anyone with access can add to any environment or pipeline group.
    - Should at least be able to restrict (defined pipelines in a repo) to a given set of environments or pipeline groups.
    - Should we use a named list of users/roles at the config-repo level to decide who gets to see the interface?

### More ideas based on comments:

- https://github.com/gocd/gocd/issues/5010: "Loading many Config Repo Pipelines takes a long time"
- https://github.com/gocd/gocd/issues/3985: "Better webhook support (paraphrased)"

### **Progress:**

Work done:

- [x] Config repo SPA https://github.com/gocd/gocd/pull/5177
- [x] Export pipeline config to pipeline-as-code format https://github.com/gocd/gocd/issues/5338
- [x] Config Repo Preflight API endpoint  https://github.com/gocd/gocd/pull/5579
- [x] Expose CR contract to plugins (Tech debt) https://github.com/gocd/gocd/issues/5374
- [x] Config-repo: helper tool  https://github.com/gocd/gocd/issues/5489
- [x] Define global/plugin SCMs as a part of the pipeline JSON/YAML https://github.com/gocd/gocd/issues/5694

Work in progress:

- [x] Config Repositories SPA Improvements (Part 2) https://github.com/gocd/gocd/issues/5650

New:

- [ ] Support for template configuration https://github.com/gocd/gocd/issues/5675

**Comment by arvindsv** [comment]
> How about fixing the existing plugin(s) to use the same shema structure as of the one provided by GoCD?

The problem with that approach will be favoring of the JSON plugin over the YAML (or even the [Groovy](https://github.com/ketan/gocd-groovy-dsl-config-plugin) one). For no great reason. From what I can see, people have settled on the YAML one over JSON, for instance, as a matter of preference.

My thought around "Export as" is to send that as a request to the plugin, and ask it to do what it needs to do to convert and show that response back to users. That way, they can copy it and check it in. So, the "Export as ..." will actually say something like: "Export as JSON", "Export as YAML", ...

**Comment by arvindsv** [comment]
> Many of the users were intrested in allowing edits to config repo entities from GoCD core. Are we considering this feature too?

> This will allow edits to the config repo entities, moving enitities from/to config repo.

True, but then GoCD controls the repo(s)? That seems a bit much. We'd need to worry about access to that repo, etc. It also changes the relationship between the plugin and GoCD. Currently, GoCD doesn't even know that there are files. The plugin just returns a JSON which is its representation of whatever it has.

If we need to do this, I'd still involve the plugin and ask it to provide a representation of a plugin (see above) and then provide that as an option to edit, to users. Then, send the edited content back to the plugin for it to manage it.

**Comment by GaneshSPatil** [comment]
> > How about fixing the existing plugin(s) to use the same shema structure as of the one provided by GoCD?
> 
> The problem with that approach will be favoring of the JSON plugin over the YAML (or even the [Groovy](https://github.com/ketan/gocd-groovy-dsl-config-plugin) one). For no great reason. From what I can see, people have settled on the YAML one over JSON, for instance, as a matter of preference.
> 
> My thought around "Export as" is to send that as a request to the plugin, and ask it to do what it needs to do to convert and show that response back to users. That way, they can copy it and check it in. So, the "Export as ..." will actually say something like: "Export as JSON", "Export as YAML", ...

Ahh I see, I was thinking it more being a core feature. But "export as" being a plugin capability makes sense!

**Comment by tomzo** [comment]
Hi all,
Here are some of my thoughts on these ideas, some of this @arvindsv has already mentioned, but that's my opinion too:

I think dedicated API endpoints and SPA showing current status of config-repos and errors per each source is number 1 priority to make user experience better.

Change plugin extension point into following model:
 * plugin must implement `parse_directory` command. (current state)
 * optionally plugin can handle `export` command which outputs configuration of pipeline/environment in plugin format. This allows to implement export functionality as an API endpoint, which then could be added to UI too.
 * optionally plugin implements some sort of presentation UI to display configuration in its own format. This allows to preview what yaml/json/groovy is currently used on the server. As a user I think having a view which shows the "native format" is more useful than e.g. a pipeline edit page in read-only state, because after sending a yaml file I know what changes I expect to see "there". If they are not there I would quickly see that.

> All entities from repo?

Yea, definitely. Pipelines are the hardest, adding any other entities should be much easier. SCMs, elastic profiles would be most convenient I guess.

# Checking errors before commit

> Idea 5: External API which checks the code, preflight, before commit.

I am not sure if this is the idea we spoke some time ago about. But the point was this:
1. User can use their code editor e.g. Atom with plugin written for it e.g. "gocd-yaml-plugin-editor". Plugins role is to parse files in current context (just like plugin does on server side) and **send that to the GoCD server** as JSON.
1. GoCD server implements checking of all those changes are correct in global context. (It tries to merge with all configuration). Returns errors to the plugin, which are then displayed in editor. 
I know that's a lot to implement but from user perspective that is most convenient tool for editing. Feedback is instant and checks with other pipelines.

# Templates

> Why not templates?

*Disclaimer: I do want to see templates support. I just feel a bit stuck finding the right solution.*

Since you ask *why not* - the number one reason NOT to have a template in config repos is an avalanche effect, which would be caused by any changes to the template, which break all the config-repos which refer to it. This is already present with current XML template + YAML pipelines referencing it.
It does not matter if the templates are to be modeled similarly to the current XML templates, or as I described in https://github.com/tomzo/gocd-yaml-config-plugin/issues/2 . The **biggest problem is managing the referenced templates across the config-repos**.
I think the most right way to model templating (either pipelines or entire config-repos) is by stating that 
 - config-repo is a software project, like any other.
 - when config-repo uses a template is a dependency of that project.

And what any reasonable software developer does with dependencies is lock its version in the source code and commit it (aka. Gemfile.lock, paket.lock, and all the other dependency managers).
So in the end my last thoughts on how a "yaml/json/whatever" template in config-repo would look like from on the user end is this:
Config-repo is still defined as today
```xml
    <config-repo pluginId="yaml.config.plugin" id="a645d411-d628-4740-a5ad-faea696c05bb">
      <git url="..." />
    </config-repo>
```
That repository aside from being able to define pipelines explicitly, it can also expand referenced templates. For example, it would define something like this:
```yaml
parameters_to_expand_template_repo_A:
  my_user_variable: abc
  my_materials:
    one: #..
    two: #...
```
In the source code of that repository there is "the lock" specifying which template and which version of template should be used.
```yaml
template_ref: # here I have no clue who would distribute those.
template_version: 0.2.1
```
The best way I could think of to implement template support is that we need additionally:
 * a separe server or endpoint in GoCD which can work as an archive of versioned "template packages". User can push template to it, server validates it with a proper "config-repo-plugin" which has a `template` capability (because the template format is plugin-specific).
 * a simple dependency manager that can talk to that server, generate lock files, update to latest.
 * `template_ref:` becomes an url to the API endpoint then. E.g. `http://go-server/api/template-repo/abc`.
 * GoCD server when checking out the config-repo materials, it additionally consumes those lock files and can get template packages, which are then passed to "parse_directory" command to the config-repo plugin. The config-repo on the SPA page then can be displayed as coming from commit "123" of the config repo, expanded from template repo commit "456".

# Improving error messages

I dream about having a config-repo plugin which behaves much like any programming language compiler and spits out line number and domain-specific or syntax error. That could be used to implement:
 * a view on the SPA which shows: `here -> line 543: you referenced a pipeline that does not exist`
 * an editor that shows those errors as you type the configuration.

That requires to implement config-repo plugin parsing at lower level and approach it like a compiler. So cannot like current `text -> yaml model -> gocd model` but by straight `tokenize yaml -> build gocd model while checking errors`

**Comment by mcico** [comment]
> GoCD server implements checking of all those changes are correct in global context. (It tries to merge with all configuration). Returns errors to the plugin, which are then displayed in editor.
I know that's a lot to implement but from user perspective that is most convenient tool for editing. Feedback is instant and checks with other pipelines.
We have implemented something like that as a separate service, where one can send the yaml files to and we send a response back with validation information. To achieve that we use parts of the gocd server core to run the validation. This way we get quite good results, but we do *not* get feedback if the configuration can be merged. If we had that as an official API we could improve the value of the validation quite a bit.

If you are interested in the solution or the idea, let us know we could contribute it to the core if desired.

**Comment by xmik** [comment]
Hi!
I use config-repos a lot (since we share a GoCD server instance with @tomzo) and also have some suggestions.

1. For me the most frequent problem is: when I create a **pipeline-as-code configuration** (e.g. a yaml file), I often make **minor mistakes** like: missing bracket, invalid indentation, repeated name of a GoCD job. This kind of mistakes could be checked by some helper tool (idea 4 by @arvindsv). It can be an external tool or some GoCD server API endpoint. For this verification kind no information on other pipelines is needed.
2. However, there is also this kind of mistakes in a pipeline-as-code configuration that needs information on other pipelines to be verified. E.g. the error: `you referenced a pipeline that does not exist`. In this case I agree with @tomzo, that it would be great to see the specific error (with specific line number and config-repo name).
3. It would be also great to see, on GoCD server GUI, **where the pipeline-as-code configuration came from**: a git repository url + git commit. This could be put:
   * either into the tab: http://go-server-host/go/pipelines/pipeline-name/4/build/1/stage_config (to replace a long cruise.xml file contents)
   * or maybe to the front page: http://go-server-host/go/pipelines for a specified pipeline, below the `Instance: material-git-ref` information. E.g. `Config-repo: git-url + git-ref`

**Comment by arvindsv** [comment]
Thank you, @tomzo, @mcico and @xmik for your thoughts. This is very helpful.

@xmik: I hear you about the verification and feedback loop. We do plan to improve it and we will keep this in mind.

@mcico: Thank you for the offer of the contrbution. I think we might take you up on it. :) Or, at least take a look at it, to learn from it. Someone will ping you here, once we get to that. Currently, we're trying to make information about the repos more visible.

@tomzo: I see what you mean about the complication with the templates. We won't jump into anything and what you lay out could be complicated for people. I'll think about it and see if there are any simpler ideas around YAML-plugin-level templating which works at the level of a repository. It might be a start, but won't be tied to GoCD templates. As you can see, I haven't put enough thought into it yet. I will do that.

Also, the external API part is similar to what we had talked about. I'm just thinking about the "API to accept the JSON and validate", for now. Integration with editors, etc. can then be done by anyone.

**Comment by stCarolas** [comment]
What about https://github.com/gocd/gocd/issues/3985 ?
There is a practice of putting pipeline code in source repo like travis but it seems like big load on git server  
We have 150+ such repos

**Comment by arvindsv** [comment]
@stCarolas Sure. Thanks for bringing it up. We could consider the state of webhook support and see if it needs to improve too. Seeing all the repos in one place, with information about when they were checked last, etc. might be useful to understand the load better.

To be clear, my preference is to handle the other things mentioned here (which are affecting getting started of this whole feature) before getting to load and performance. Thanks again!

**Comment by arvindsv** [comment]
@stCarolas Also, https://github.com/gocd/gocd/issues/5010 seems similar.

**Comment by ketan** [comment]
I did a couple of spikes over the weekend and here's what I was able to do:

- Create [java models](https://github.com/ketan/gocd-groovy-dsl-config-plugin/tree/json-and-yaml-spike/dsl/src/main/java/cd/go/contrib/plugins/configrepo/groovy/dsl) for the current state of config repos. Should be possible to add more models to add support for other entities in the future (elastic profiles, SCMs...)
- Validation on the models. Given an incomplete or bad attributes on the model, I'm able to validate if the inputs are correct, and pinpoint the location where the error is at.
- Generate a [JSON schema](https://github.com/ketan/gocd-groovy-dsl-config-plugin/blob/json-and-yaml-spike/json-schema/src/main/java/cd/go/contrib/plugins/configrepo/groovy/dsl/jsonschema/Main.java) that can validate any input JSON. Currently, the input json is the same JSON that's returned to the GoCD server. I understand that is not exactly desirable, and can be changed. The point here was to be able to deserialize from the JSON, and validate using the JSON schema.
- Deserialize a YAML and validate that using the same JSON schema. Since JSON and YAML are in some ways "interchangable", they can both be validated using the same JSON schema to get useful error messages.

**Comment by tomzo** [comment]
@ketan that's nice.
How are those java models different from [the ones in extension point](https://github.com/gocd/gocd/tree/master/plugin-infra/go-plugin-access/src/main/java/com/thoughtworks/go/plugin/access/configrepo), would you intend to replace the ones in core?
I guess you generated the schema from those models, so perhaps schema could be something published together with each GoCD release. 
Also do you think we could release a jar which has both the json schema, models and validation rules. So that it can be used by
 - all plugins
 - (future) editors
 - maybe actually server extension point could use the same library for validations?

**Comment by laurence-hubbard** [comment]
@arvindsv @GaneshSPatil @tomzo 
> Idea 3: Convert existing pipelines to YAML / JSON ("Export as").

Not quite what you're looking for but I've had a go at writing a conversion tool for going from XML to JSON:
https://github.com/laurence-hubbard/gocd-config-conversion

**Comment by arvindsv** [comment]
@laurence-hubbard Thanks for this! Sorry, I forgot to respond.

Keeping the XML version in sync will be a challenge. @ibnc is working on integrating an export functionality into GoCD itself - by using the same communication we already use with the plugins. Let's take a look at that (soon) and then decide what to do. Hopefully, you can all try it out in the upcoming release of GoCD.

**Comment by ibnc** [comment]
> @arvindsv @GaneshSPatil @tomzo
> 
> > Idea 3: Convert existing pipelines to YAML / JSON ("Export as").
> 
> Not quite what you're looking for but I've had a go at writing a conversion tool for going from XML to JSON:
> https://github.com/laurence-hubbard/gocd-config-conversion
> 
> Happy to have a go at adding it into GoCD directly somewhere as an export function, but not sure if it will hold up to differing versions of XML.

Part of the problem is that GoCD is and must remain agnostic to the data format used by the config in repo plugins. So, the conversion will be the plugin's responsibility. 

The work the Go server will do is to request an export ([by serializing the necessary data to JSON](https://github.com/gocd/gocd/blob/b8cbce628afca8b20726e5fbd81ebea1e20091fe/server/src/main/java/com/thoughtworks/go/config/ConfigConverter.java)), and handle the export after the plugin has done the conversion. The first part is done, and the latter is in progress.

The YAML and JSON plugin conversion work is done. The only remaining plugin that doesn't have the export implemented is the groovy plugin

**Comment by sheroy** [comment]
Idea: Create a new view for the pipelines created when a new config repo is added. Link to this view from the config repo listing page.

**Comment by rajiesh** [comment]
This is an ongoing effort still we complete what we have discussed here, so moving it to 19.2

**Comment by zerolaser** [comment]
@adityasood Will this released in 19.2.0 ?

**Comment by ankitsri11** [comment]
@zerolaser most of the work on this epic is completed and available as part of GoCD 18.12 and onwards. You can read more [here](https://www.gocd.org/releases/#18-12-0) and [here](https://www.gocd.org/releases/#19-1-0).

As mentioned earlier by Rajiesh, this is an ongoing effort and have kept this issue open until then.

Is there any specific issue you are looking for?

**Comment by maheshp** [comment]
Closing the epic since most of the items are addressed, will create issues for further enhancement.
