### ISSUE TITLE
Thoughts about "drain mode" for GoCD

### ISSUE THREAD

**Issue by arvindsv** [gocd/gocd#5190]
I've been asked about this, a few times: A good way to know when a GoCD server (the whole system actually) is ready and in a good place to be brought down for either a restart or an upgrade.

Considerations:

  - Don't be busy checking for material updates
  - Agents should all have finished work (should be idle or missing or lost contact)
  - There should be no "create-agent" calls waiting (elastic agents)
  - No new jobs should be assigned to agents
  - No new requests for triggering pipelines and approval of manual gates should be accepted (UI / API)
  - Should ideally show a message to all users

@gocd/committers What is missing? Is this a bad idea for some reason?

**Comment by ketan** [comment]
> - There should be no "create-agent" calls waiting (elastic agents)

No way to know that. No agent is currently building seems like a more sensible option to me.

> - Should ideally show a message to all users

Likely in a more prominent location where users acknowledge seeing this. Aka not server health messages :)

> Is this a bad idea for some reason?

I don't see it as a bad idea.

**Comment by arvindsv** [comment]
> Likely in a more prominent location where users acknowledge seeing this. Aka not server health messages :)

Yes, yes. Banner, etc. :)

> > There should be no "create-agent" calls waiting (elastic agents)
> No way to know that. No agent is currently building seems like a more sensible option to me.

I mean that the scheduling subsystem should be turned off. And we would show that there are jobs waiting for scheduling. If they have been picked up (in progress of scheduling), we could decide it's not ready.

I mentioned elastic agents explicitly to say that we shouldn't forget them.

**Comment by ketan** [comment]
For clarity, here's what I'd think means "ready to shutdown" after admin clicks some "maintenance mode" button:

- show a visible message (Q: persist to db, in case someone shuts down the server midway?)
- stop all MDU
- stop all scheduling
- any agents that ping for work receive nothing (even if there are scheduled jobs that that can possibly be assigned). If create agent calls were made and elastic agents are booting up, they'll just sit idle, until the plugin decides to terminate them. This termination may as well happen after the server comes back online.

Once any agents that are currently building complete their jobs, we can notify the admins that the server is now drained and can be shut down. We may possibly even shutdown automatically on behalf of an admin, if they prefer so, although I personally don't like this option.

**Comment by maheshp** [comment]
>Once any agents that are currently building complete their jobs, we can notify the admins that the server is now drained and can be shut down. We may possibly even shutdown automatically on behalf of an admin, if they prefer so, although I personally don't like this option.

We might have to think about how to handle long running jobs which could be building when the server goes into maintenance mode. If these jobs are not cancelled the server could end up being in the maintenance mode for too long. Should we consider listing all currently building jobs when the server goes in the maintenance mode and give an option to Admins to cancel them.

**Comment by arvindsv** [comment]
>  If these jobs are not cancelled the server could end up being in the maintenance mode for too long

Yes.

> Should we consider listing all currently building jobs when the server goes in the maintenance mode and give an option to Admins to cancel them.

My idea is that the maintenance mode page, the one with the button, will also show the status:

- Material update is stopped
- Scheduling is stopped
- Waiting for these jobs to finish:
   Job 1 on agent 1
   Job 2 on agent 2
   ...

Cancelling would be a nice option.

**Comment by GaneshSPatil** [comment]
Few points:
* During drain mode, GoCD should allow making config changes.
* Allow users to get an email notification about the maintenance mode. (Started/Ended)

Few problems:
* During maintenance mode, Users can add new config-repos to the server. But, as the MDU is turned off, no new pipelines will be shown. 
* Affects Analytics:
   - VSM analytics will have time gaps between decendent pipeline runs, as no new pipelines will be scheduled during maintainance mode. This will affect the `avg cycle time` on the trends chart and time on `vsm time distribution chart`.
   - Few pipelines could be scheduled (but not assigned), such pipeline-runs will have longest wait time. This will affect pipeline level analytics.
   - Agents will not be building any jobs during this time period, resulting in underutilization.

**Comment by GaneshSPatil** [comment]
#### GoCD Maintenance Mode

- [ ] Persist the maintenance mode state in GoCD (either cruise-config.xml or DB)
- [ ] Create an API to allow users toggling the maintenance mode state
- [ ] Do not perform MDU under maintenance mode
- [ ] Do not schedule new pipelines under maintenance mode
- [ ] Do not assign scehduled jobs to agents
- [ ] Do not allow work trigger:
	- [ ] No manual trigger of pipelines
	- [ ] No manual stage trigger, stage rerun
	- [ ] No timer triggered pipelines
- [ ] Do not allow forcing MDU on config repos (current WIP PR from @marques-work)
- [ ] Show flash message banner (alert callout) on all GoCD pages about maintenance mode
- [ ] GoCD Maintenance Mode SPA
    - [ ] Allow users to toggle maintenance mode state from UI
    - [ ] Show scheduled jobs which will not be assigned to agents during maintenance mode
      	- [ ] Create an internal API to fetch scheduled jobs information
      	- [ ] Show scheduled jobs information on the UI.
    - [ ] Show building jobs information along with the assigned agents
    - [ ] Allow users to cancel building/scheduled jobs
    - [ ] Show information about currently disabled sub-systems of GoCD (MDU, work-assignment, etc. wont work)
	- [ ] Show information affected sub-systems of GoCD (Config-repos, analytics)
    - [ ] Information about is server completely drained?
    - [ ] When GoCD server is not under maintenance mode, show content about what maintenance mode is.
- [ ] Send email notification to users about maintenance mode.

**Comment by arvindsv** [comment]
Might be able to reuse parts of mode-aware filter? I'd think we'd pause larger subsystems such as MDU and scheduler (and their timer).

@GaneshSPatil - The list looks ok. Can't think of others at this time.

**Comment by arvindsv** [comment]
> VSM analytics will have time gaps between decendent pipeline runs, as no new pipelines will be scheduled during maintainance mode.

That's ok. Those pipelines were really not scheduled at those times.

**Comment by arvindsv** [comment]
My opinion about what is definitely necessary / priority:

~~- [ ] Persist the maintenance mode state in GoCD (either cruise-config.xml or DB)~~
- [ ] Create an API to allow users toggling the maintenance mode state
- [ ] Do not perform MDU under maintenance mode
- [ ] Do not schedule new pipelines under maintenance mode
- [ ] Do not assign scehduled jobs to agents (see note below)
- [ ] Do not allow work trigger:
	- [ ] No manual trigger of pipelines
	- [ ] No manual stage trigger, stage rerun
	- [ ] No timer triggered pipelines
- [ ] Do not allow forcing MDU on config repos (current WIP PR from @marques-work)
- [ ] Show flash message banner (alert callout) on all GoCD pages about maintenance mode
- [ ] GoCD Maintenance Mode SPA
    - [ ] Allow users to toggle maintenance mode state from UI
    - [ ] Show scheduled jobs which will not be assigned to agents during maintenance mode
      	- [ ] Create an internal API to fetch scheduled jobs information
      	- [ ] Show scheduled jobs information on the UI.
    - [ ] Show building jobs information along with the assigned agents
    ~~- [ ] Allow users to cancel building/scheduled jobs~~
    - [ ] Show information about currently disabled sub-systems of GoCD (MDU, work-assignment, etc. wont work)
	- [ ] Show information affected sub-systems of GoCD (Config-repos, analytics)
    - [ ] Information about is server completely drained?
    - [ ] When GoCD server is not under maintenance mode, show content about what maintenance mode is.
~~- [ ] Send email notification to users about maintenance mode.~~


### Questions (and thoughts):

> - [ ] Persist the maintenance mode state in GoCD (either cruise-config.xml or DB)

Why? If it restarts, there's no point of maintenance mode.

> - [ ] Do not assign scehduled jobs to agents

Don't forget the race condition of "Assigned" jobs not yet picked up by agents. Either due to the 5-second ping loop or due to run on all agents.

**Comment by arvindsv** [comment]
Also, don't allow any other POSTs, PUTs or DELETEs?

**Comment by arvindsv** [comment]
A thought: Even though config update won't be allowed, it'll happen through the filesystem (unless the spring timers are also stopped). Since MDU and scheduling are stopped, nothing will happen based on it?

**Comment by GaneshSPatil** [comment]
@arvindsv --
> Don't  forget the race condition of "Assigned" jobs not yet picked up by  agents. Either due to the 5-second ping loop or due to run on all  agents.
--

**Comment by GaneshSPatil** [comment]
@arvindsv -- As there could be many materials performing MDU and could take a while to do so. Should we be showing materials performing MDU on drain mode SPA?

**Comment by arvindsv** [comment]
> IMO, If a job has been assigned, we should let it build. As we store the job assignment state in the DB. It's up to the admin users to cancel such jobs.

True. My thought about the race condition was if an agent was assigned and then goes missing. Based on our conversation: "After a while, the agent will be rescheduled and it'll then be safe for the server to restart". So, no special action needed for this case, is what we decided.

The API response probably needs to indicate whether each sub-system considers itself to be "drained".

**Comment by arvindsv** [comment]
> During drain mode, state of the server shouldn't change. If we don't allow modifying config via XML edit or via GoCD APIs. We shouldn't allow modification through file system as well.

That's fine.

**Comment by arvindsv** [comment]
> As there could be many materials performing MDU and could take a while to do so. Should we be showing materials performing MDU on drain mode SPA?

Yes, ideally, materials performing MDU should finish, before the MDU considers itself safe.

**Comment by rajiesh** [comment]
Verified on 19.1.0 (8442-53886b50565a61edc3d4ded04df2616c84db19ac)
