### ISSUE TITLE
Information about jobs using elastic profiles

### ISSUE THREAD

**Issue by GaneshSPatil** [gocd/gocd#5209]
##### Issue Type

- Feature proposal

##### Summary

Show the list of [pipeline/stage/job]s using an elastic profile from the elastic-agent-profiles page.
As of now, It's really hard to know which profile is being used by which job(s).

\cc @gocd/committers

**Comment by arvindsv** [comment]
We should also consider printing out information about the agent, at the top of a job (console). Info from the plugin, about the agent it is starting, with information such as docker image, etc. Whatever is relevant.

**Comment by ketan** [comment]
Right now I rely on clicking the delete button to know about that. The error message there is still not good enough. Could definitely use improvement.

**Comment by bdpiparva** [comment]
closing as duplicate of https://github.com/gocd/gocd/issues/5209

**Comment by bdpiparva** [comment]
### Todo:

- [x] Move elastic profile api to spark (#5258)
- [ ] Internal api to get elastic profile usages
- [ ] Assocciate elastic profile to job from Elastic profile SPA

**Comment by bdpiparva** [comment]
## API
Here is the API example request-response

### Example 1

#### Request
```bash
curl 'http://localhost:8153/go/api/elastic/profiles/profile_2/where-used' \                                                                                           
      -u 'admin:badger' \
      -H 'Accept: application/vnd.go.cd.v1+json' | jq .
```

#### Response

```json
[
  {
    "pipeline_name": "Foo",
    "stage_name": "Foo_stage",
    "job_name": "Foo_job2"
  },
  {
    "pipeline_name": "Test",
    "stage_name": "Stage1",
    "job_name": "job2"
  },
  {
    "pipeline_name": "Foo",
    "stage_name": "Foo_stage",
    "job_name": "Foo_job1"
  }
]
```

**Comment by GaneshSPatil** [comment]
> `http://localhost:8153/go/api/elastic/profiles/profile_2/where-used `

Just a thought, `/foo_profile/where-used` => `/foo_profile/references`?

**Comment by bdpiparva** [comment]
@GaneshSPatil  - We are leaning towards following options:

1. where-used
2. usages

@gocd/committers - WDYT?

**Comment by arvindsv** [comment]
I like `references` too. If not, `usages` seems ok.

**Comment by rajiesh** [comment]
@bdpiparva Currently this API response has pipeline/stage/job name. If the stage and job is defined in a template and used in pipeline still this API returns Pipeline/Stage/Job names. That breaks the `Go to job settings` link on the profile usages page. Will create a separate issue where we can discuss how to improve this better

**Comment by adityasood** [comment]
verified on 18.12.0-8222
