### ISSUE TITLE
Elastic Agent Improvements

### ISSUE THREAD

**Issue by GaneshSPatil** [gocd/gocd#5372]
##### Issue Type

- Feature enhancement

##### Summary
A list of features that can be improved on Elastic Agent Plugins.

- [ ] Information about jobs using elastic profiles (#5209)
- [ ] Add Plugin Settings change call to EA extension. So that, plugin could perform cleanup on older cluster.
- [ ]  Add Server Health Message about Plugin Settings not configured. Currently, the only way to know is ping-failure error in server logs.
- [ ] Do not perform any operation if plugin-settings is not configured. Ping fails, Status Report Page blows up with 500.
- [ ] Allow support for multi-cluster environment.
- [ ]  Add a link to the plugin status report from agent status report page (#4476)
- [ ] Add server health messages for incorrect Docker Elastic agent plugin profile configuration (detailed issue #3914)

**Comment by GaneshSPatil** [comment]
\cc : @gocd/committers @sheroy

**Comment by arvindsv** [comment]
@GaneshSPatil I think we should do this based on talking to some people and coming up with a flow. For instance, whenever I'm trying to use some elastic agents, I do this:

1. Go to elastic agent profile.
2. See that an option I want is not there.
3. Remember that plugin settings is the place it's going to be at.
4. Search for link to plugin settings in that page.
5. Don't find it.
6. Go to Admin -> Plugins.
7. Find the plugin and click on Settings.

By watching others using it, we might learn whethere cases like this are common or not.

Also, we need to prioritize this, before we start. We might have too many things going on right now.

**Comment by GaneshSPatil** [comment]
@arvindsv -- closing this issue as the above-mentioned points are either fixed and not anymore relevant after the cluster profile changes.
Also, we will create separate issues for the elastic agent related work that has been decided after the EA workshop.
