### ISSUE TITLE
Disallow POSTs, PUTs and DELETEs during Server Maintenance Mode

### ISSUE THREAD

**Issue by GaneshSPatil** [gocd/gocd#5450]
epic: #5190 

##### Issue Type

- Feature proposal

##### todo

- [x] Do not Allow creation of new GoCD entities (block POSTs)
- [x] Do not allow updating existing entities (block PUTs)
- [x] Do not allow deleting existing entities (block DELETEs)
- [x] Do not allow triggering pipelines, stages, job reruns.

- [x] Allow cancelling stages.

**Comment by GaneshSPatil** [comment]
Responses:
- [ ] Should return a JSON response for API headers
- [ ] Should return an HTML error (similar to backup-in-progress) for UI pages making POST calls.
       Eg: edit cruise-config.xml or create pipeline through UI.
  - [ ] Should show information about drain mode approver and time.
  - [ ] Should link to server drain mode SPA from HTML response.

**Comment by GaneshSPatil** [comment]
@ketan -- Not sure if we need to disallow logouts. 
The point of maintenance mode is to make sure server isn't doing anything and safe to take down.
Even though logout changes the DB state, the server config and build state is not affected by it.

Secondly, if we allow users to login during the maintenance mode, they should be allowed to logout as well.

\cc: @arvindsv @maheshp

**Comment by arvindsv** [comment]
Yes, I think that should be ok (to allow log outs), though we should understand exactly how the DB is changed during log out and see if it should not happen.

**Comment by GaneshSPatil** [comment]
Done as part of #5466 #5454 #5450
