### ISSUE TITLE
Multi-cluster Support for Elastic Agents

### ISSUE THREAD

**Issue by GaneshSPatil** [gocd/gocd#5538]
##### Issue Type

- Feature enhancement

#### Tasks:
  - [x] Define Elastic Agent Extension v5 (#5937)
  - [x] Migrate existing Elastic Agent plugins to implement v5 extension
  - [x] Support for cluster config entity in GoCD (Migration + CRUD) (#5938)
  - [x] Bump Up Elastic Agent Profiles API to support clusterProfileId (#5983)
  - [x] Migrate Existing EA profiles to point to cluster config using `migrate-config` plugin api call.
  - [x] Fix Elastic Agent Profiles UI to work with cluster config.
  - [x] Remove ability to configure plugin settings for plugins implementing EA extension v5
  - [x] Write a cluster profiles SPA to manage cluster profiles
  - [x] document elastic agent extension v5
  - [x] SPA (#6045)
  - [ ] Show a server health message when v4 plugins are used.
  - [x] Store cluster profile information on plugin infos API

**Comment by GaneshSPatil** [comment]
Current Problems with EA plugins:

* No Multi-Cluster support
* Overriding plugin-setting fields at each individual profile causes a lot of duplication and makes it harder to maintain the profiles, as, change in the field value will require changing it at all profiles.

**Comment by GaneshSPatil** [comment]
Proposed solution:

* Allow users to define named-clusters at the plugin-settings level and then refer to these clusters from elastic profiles level. Users can define any number of named clusters.
Even if just a small field needs to be overridden, users should create a new cluster. 
  Eg: On kubernetes, if a user wants to use two namespaces of the same cluster. A user needs to define two different clusters with same cluster URL but different namespaces.

**Comment by bdpiparva** [comment]
- Approach 1:
   - A new endpoint for the cluster configuration. This allows a user to provide cluster configuration globally(credentials, region etc..)
   - Refer the cluster settings from an elastic profile.
   - Plugin settings will contain only global configuration no credential related.
   - `Create agent`, `validate-profile` and `should assign work` call will get profile and cluster credential in the request

- Approach 2:
  - Modify the existing plugin settings an take a culster settings as JSON, YML or Groovy
  - Validate configuration on save of the settings for `uniqueness` of cluster config name and `mandatory` fields
  - Rest of the stuff will remain the same. This is simple but implementation may vary from plugin to plugin

**Comment by arvindsv** [comment]
@bdpiparva My preference would be approach 2. Approach 1, beyond being more work, introduces a new concept and the settings will in three places: plugin-settings, cluster-settings and profile. Users have to (mostly manually) put it all together in their head.

Approach 2 puts the onus of the settings and cluster support on the plugins. That could cause it to be inconsistent for sure, but given that endpoint provides enough flexibility to implement this, they should do it themselves. That way, if "cluster" is the wrong terminology for this in some plugin, then a user won't have to map that concept into "cluster" to understand what is happening.

For instance: Consider the case mentioned by @GaneshSPatil above, where the cluster is the same, but the namespace is different. If we ask the k8s plugin to implement it, then it might use a term more appropriate than "cluster" and lead to less confusion.

**Comment by GaneshSPatil** [comment]
@arvindsv -- Regardless of permissions, 
I think we can show the "**non-credential**" fields in read-only mode on the elastic-profiles page. 

Showing the cluster URL, the username used and basic configurations such as VPC, EC2 config should be OK?

**Comment by GaneshSPatil** [comment]
### Elastic Agents Support for multi cluster

Currently, the plugin settings allows users to define only one cluster configuration. 
Today (plugin-setting == cluster-configuration)

To allow defining multiple clusters, we are thinking of allowing users to define multiple plugin settings.

An admin user will define multiple named plugin settings and each profile will be associated with one of the pre-defined plugin settings.

Resolution of the associated plugin-settings with the elastic profile will be handled by GoCD core.

---

### Implementation Details:

* GoCD will start supporting (only Elastic agent plugin) settings as a list of plugin settings. 
  Each setting will be known as cluster setting having a unique name.

* User will associate each elastic agent with the named cluster settings.

* For the create agent request, GoCD server will pick the appropriate plugin settings associated with the elastic agent profile and will send both to the plugin for agent creation.

* The plugin settings view will be a tabular view. Each tab will represent the unique named cluster settings.

* The Plugin Status report page view will be tabular view. Each tab will represent the status report of the cluster.

---

### Few points:

* #### But it still has duplication? 
  Yes, Allowing users to define multiple named clusters will result into some duplication of common properties based on the usecase.  
  This duplication will be lesser and manageble than the allowing overrides at individual profile level.

* #### GoCD Server URL is always the same across all cluster settings?
  Yes. GoCD Server URL is the only common field which value will be same across all the named cluster settings.
  Ideally, Plugins shouldn't be asking for this information from the users. GoCD Server and plugin internally should figure out the correct GoCD server URL.

* #### Should we allow overridding cluster properties at elastic profile?
  - No. If a user wants to change the cluster settings, they should create a new setting.
  - Allowing users to override properties at profile level will lead to lot of duplications across multiple profiles.
  - Also, profiles defining cluster configuration causes computation of status report pages very difficult.

* #### Why not Cluster as a GoCD entity?
  - Defining a new entity for Elastic Agents brings in more complexities as the configurations will be defined at 3 places (cluster, plugin settings and profile) and the heirarchy of overridden stuff is hard to understand.
  - Migration of existing settings and profiles is difficult.

* #### Why not cluster as a concept in plugin settings?
  - This will make multi-cluster support a problem of plugin authors. Not all the plugins will support this capability.
  - The implementation to support multi-cluster will differ based on how plugin authors choose to implement it.

* #### Plugin Settings Migration?
  The current plugin settings will be named "default" and will be associated with all the existing profiles.

* #### Is cluster the right term?
  May be not. In the context of kubernetes it seems right, but for Openstack/Azure, the settings are just a bunch of configurations where the VMs are brought up to run the agent.

---

### WHats the UX change?

* #### Plugin Settings View
  - Plugin Settings view changes to a tabular view with the existing settings migrated to the default cluster settings.
  - (Maybe) Show the list of profiles consuming the current cluster settings.

* #### Elastic Profiles
  - Existing elastic profiles will be associated with the default cluster settings.
  - The read only view of associated cluster settings will be displayed inline for the users to know which cluster the current elastic agent will be run on.
  - Link from read only cluster settings view to go to plugin settings for making any changes. 
    Do no allow inline edit of cluster settings from profile, as the same cluster will be used at other places, modifying the cluster inline will affect other profiles.
  
* #### Plugin Status Report Page
  Plugin Status report page changes to a tabular view showing the status reports of each cluster.

* #### Agent Status Report Page
  Agent Status report page remains unchanged.

---

### Unknowns?

* Changing plugin settings call only for elastic agents.
  Plugin settings call is common across all the plugins. It needs to change to support multiple plugin settings only for EA extension.

* Existinh Plugin settings and Elastic Profile Migration to support multi-cluster model.

---

\cc: @gocd/committers @arvindsv @smarker @varshavaradarajan

**Comment by ketan** [comment]
>     * GoCD Server URL is always the same across all cluster settings?

I don't think this is necessarily the case. It should be possible to access the same host via different hostnames, in between different clusters. We ourselves do this. We use `build.gocd.io` for hosts inside AWS and `build.gocd.org` for elastic hosts outside of AWS.

**Comment by bdpiparva** [comment]
> To allow defining multiple clusters, we are thinking of allowing users to define multiple plugin settings.

I think this should be a plugins capability whether the plugin will support the multiple settings or not. GoCD still does the migration even if the plugin doesn't support multiple configurations and associate it with all the profiles. Only the creation of the second config won't be allowed.

> The Plugin Status report page view will be tabular view. Each tab will represent the status report of the cluster.

Leave this to the plugin author. We should provide all settings and let them figure out the view. @GaneshSPatil WDYT?

> GoCD Server URL is always the same across all cluster settings?

No need to handle this as there is server info processor for that. If plugin author really needs the server URL other then what server info is returning then that can be defined as part of the plugin settings.

**Comment by GaneshSPatil** [comment]
> I think this should be a plugins capability whether the plugin will support the multiple settings or not. GoCD still does the migration even if the plugin doesn't support multiple configurations and associate it with all the profiles. Only the creation of the second config won't be allowed.

Yeah, make sense. As the settings fields are completely in control of the plugin, the plugin can decide if they want to support mutli-cluster via multiple plugin-settings or some other mechanism.

**Comment by maheshp** [comment]
Irrespective of where the cluster settings are stored I would prefer not going to multiple places to configure and view the cluster settings and the profile.

Ideally if I am configuring an elastic agent plugin, I would prefer an option to configure a cluster and create multiple profiles for the same. The cluster configuration and the related profiles to should be grouped together which would make viewing the entire cluster + profile easier.

**Comment by GaneshSPatil** [comment]
### EA Support for Multi Cluster using Cluster Configurations

GoCD introduces cluster as a new concept in GoCD core. All the elastic agent plugins will define a named cluster as part of cluster configurations instead of defining it using plugin settings. The named cluster config will be associated with the elastic agent profile. The users can define as many named clusters as they want.

The newer elastic agent extension will stop supporting defining and consuming plugin settings.

#### Tasks:
  - [ ] Define Elastic Agent Extension v5
  - [ ] Migrate existing Elastic Agent plugins to implement v5 extension
  - [ ] Support for cluster config entity in GoCD (Migration + CRUD)
  - [ ] Migrate Existing EA profiles to point to default cluster config
  - [ ] Fix Elastic Agent Profiles UI to work with cluster config.
  - [ ] Remove ability to configure plugin settings for plugins implementing EA extension v5


\cc: @gocd/committers  @sheroy

**Comment by GaneshSPatil** [comment]
@arvindsv @maheshp @bdpiparva @ketan -- How about calling the cluster "**Deployment Profile**"?

Deployment profile defines where the Elastic Agents will be deployed/run.  
A deployment profile can either be a cluster configuration or a set of properties that define where the agent will run (eg: VM).

**Comment by varshavaradarajan** [comment]
@GaneshSPatil - this is what I understood from the above comments:

- For each EA plugin, configure plugin settings (agent autoregister timeout?, properties common to all clusters, if any)
- For each EA plugin, configure clusters or "Deployment profiles", which is a new global entity that is being introduced?
- For each EA profile, refer to the already defined cluster-config by id and configure profile level details like agent image, memory, env vars
- For each job, use the EA profile id

Is that right?

I find that for EA, the amount of setup that is to be done seems to increase a lot. In order to avoid duplication of cluster related information, a new entity must now be configured. Its good that the cluster info that is currently in plugin settings will be migrated to the cluster-config global entity. But this still becomes a complex workflow, I think. Because it involves  at least 3 levels of referencing. I may have misunderstood. 

This is just an idea. Maybe I haven't thought it out fully, please feel free to ignore it:

- Get rid of plugin settings. All the info in the plugin settings can be migrated over to the profile?
- Change EA profile settings from form to a json (similar to what you have for k8s pod yaml). Let the id and plugin id be the only mandatory data to be entered. Let all of the config be template-able. Meaning, allow for each value to be something that can be overridden (like in pod yaml, there is the  {{ POD_POSTFIX }} that users should change) at the job level. Those who are okay with some setup info duplication can clone existing profiles, change only the values they want and store as a new EA profile config.
- In the job settings, when a profile is referenced, display the json for view. When the profile is referenced, check that the plugin's required fields are actual values ( not templated like {{ POD_POSTFIX }} ). If some values are to be overridden, show the fields that the plugin deemed mandatory for users to enter the values. Do not perform any validation beyond that. An error can be displayed on the job console if the agent can't be brought up for the job. 
- So, for pipeline config, along with elastic agent id, sometimes, extra overridden info needs to be stored. This involves changing the xsl to have an additional optional element (let's call it EAProfileOverride, ask Duck for naming) when elastic agent profile id is specified.  It also involves changing the pipeline config API, config-repos.
- Because this is at a job level, templates will be involved. But, I think that pipeline parameters should be disallowed for now. That is, the EA profile values that are going to be overridden at the job level should not accept pipeline parameters. This involves changing the template config API to include EAProfileOverride.

May be this is too complicated as well, I don't know. Just a suggestion.

**Comment by GaneshSPatil** [comment]
@varshavaradarajan -- Extremely sorry for the [above](https://github.com/gocd/gocd/issues/5538#issuecomment-469141514) response.
I think I wasn't clear enough with the decided approach/intention.

We are **_NOT_** planning to keep 3 entities (plugin-settings, clusters, and profiles) to specify configurations of Elastic agents. We will get rid of `plugin-settings` in favor of `cluster configuration`.

So, Users can define multiple clusters and associate a cluster with the profile.
A cluster configuration defines the environment where the elastic agent will run. And the elastic profiles define which elastic agent and how to run.

---

> All the info in the plugin settings can be migrated over to the profile?

Defining the cluster configurations inline with the profile might cause followin issues:
1. Lot of configuration duplication at the each profile.  
   This was the main reason for allowing users to configure cluster at plugin settings.

2. More complexity at the plugin implementation as the on each request from the request information we need to create 2 entities cluster and the profile to deal with the deployment environment and the elastic agent application to deploy.

3. Status reports are a mess to compute with inline profiles.

> Change EA profile settings from form to a json

This depends on the plugin as the view and the configuration properties are defined by the plugin. We can define this as a guideline but can't make it a restriction. 
The other implementation for this could be, don't ask for view from the plugin and use the JSON/YAML template view and only rely on the fields from the plugin. But that seems too much of work for GoCD.

---

> Those who are okay with some setup info duplication can clone existing profiles, change only the values they want and store as a new EA profile config.
and
> In the job settings, when a profile is referenced, display the json for view. When the profile is referenced, check that the plugin's required fields are actual values ( not templated like {{ POD_POSTFIX }} ). If some values are to be overridden, show the fields that the plugin deemed mandatory for users to enter the values. You can also allow for users specifying additional key values, but they can be ignored if the key isn't present in the json? Do not perform any validation beyond that. An error can be displayed on the job console if the agent can't be brought up for the job.

The real reason for introducing a new entity was to support multi-cluster support. The suggested approach would let users configure multiple clusters using field overrides, but this is still possible to do at the profile level (without a change in core). 
Allowing overrides at profile or at the job-config will result into alot of duplication and unnecessary complexities at multiple places.

---

\cc: @arvindsv @sheroy

**Comment by sheroy** [comment]
Sorry I'm late to the party. 

@varshavaradarajan I think your idea of a template based EA profile configuration yaml at a job level is interesting. I think it's a fresh take on configuring EAs, and I agree it reduces the number of levels of configuration. 

I feel that introducing the concept of named clusters as a separate concept is still valuable for the following reasons:
1. I would rather see a list of named cluster configurations in one place rather than spread across job definitions, so I can get a view of the set of configured clusters. 
2. It makes the status report page simpler to grok and manage, as @GaneshSPatil mentioned. 
3. I think cluster configuration and EA profile configuration are separate concerns and don't really need to mixed. They could be configured by different individuals with different levels of authorization. 

\cc: @arvindsv

**Comment by sheroy** [comment]
> @arvindsv @maheshp @bdpiparva @ketan -- How about calling the cluster "**Deployment Profile**"?

I like "Deployment Profile" or "Deployment Target"

**Comment by arvindsv** [comment]
@sheroy I think deployment profile/target can be confusing, given the fact that "deployment" means something else to most people. They'll be thinking about their own apps' deployment.

Cluster profile is also somewhat ambiguous in some cases. But, my preference is still that.

**Comment by sheroy** [comment]
@arvindsv, I agree, let's go with "Cluster Profile".

**Comment by rajiesh** [comment]
Verified on 19.3.0 (8959-259d1f79e361875995072e5c1fcc9cbda7ccc600). Enhancing server health message to show deprecation warnings will be tracked by separate issue
