### ISSUE TITLE
User summary page epic

### ISSUE THREAD

**Issue by vrushaliwaykole** [gocd/gocd#5564]
Epic story to track progress of the new user summary page:

- [x] Show list of users (#5553)
- [x] Search API for user search (#5560)
- [x] API changes (#5558)
- [x] Search modal for users page (#5563)
- [x] Ability to add users using interface, (or just rely on search to be able to add users)?
- [ ] Ability to perform bulk operations from UI (enable/disable/delete, change roles, make admin...)

**Comment by GaneshSPatil** [comment]
related issues: https://github.com/gocd/gocd/issues/71

**Comment by rajiesh** [comment]
Verified on 19.2.0 (8639-9ba73d561b80d9d4e20dbf903aaeb3d29fcd3ab4)
