### ISSUE TITLE
Move role configuration spa to component based

### ISSUE THREAD

**Issue by kritika-singh3** [gocd/gocd#5602]
##### Summary
The current spa is implemented using mithril. This issue is to move it to typescript.

##### Todo
- [x] Add a toggle to switch between old SPA and new SPA(#5630)
- [x] Move SPA to typescript(#5630)
- [x] Update functional tests for the same (https://github.com/gocd/ruby-functional-tests/pull/264)
