### ISSUE TITLE
Config Repositories SPA Improvements (Part 2)

### ISSUE THREAD

**Issue by GaneshSPatil** [gocd/gocd#5650]
epic: https://github.com/gocd/gocd/issues/5175

##### Issue Type

- Feature enhancement

#### New features (ordered by priority):

- [x] Show config repo parsed information
	- [x] last known commit
	- [x] last good commit
	- [x] metadata of the last good commit (author, commit_msg, sha)

- [x] Show errors related to each config repository
	- [x] config repo parsing errors
	- [x] Config entity validation errors

- [x] Check connection for config repo materials

- [x] Internally force update a config repo upon creation (either via UI or via API). (#5679)

- [x] Show MDU for config repo material in progress information on the SPA.
	- MDU can be scheduled externally by forcing an update from the SPA/API or timer based MDU within GoCD. 
	A user must know if the MDU is in-progress for the material so that the user can make a decision of scheduling another update or not.
	Also today, a user forces an update, there is no feedback around the progress of the update apart from just a message saying `An update was scheduled for this config repository.`

- [x] Show real-time data on the SPA. (#5655)
	Users shouldn't need to refresh the page. Maybe introduce ajax_polling

- [ ] Improve config repo validation error messaging.
    - [ ] Perform schema validation to check the existence of mandatory fields instead of NullPointerExceptions.
      Example: For a config repo pipeline git material, if URL field is not specified, the following error is shown in the server health messages:
       `runtime; - Unexpected error when handling plugin response java.lang.NullPointerException`

#### Bugs:
- [x] Show error if invalid repo url is provided. (#5651) (#5652)
	  Currently, the config repo material clone error is populated in the server health messages only for a fraction of time (5 secs) and then removed.

- [x] Improve page operation messages
	- [x] `An update was scheduled for this config repository.`
		Instead of saying this, change it use the config_repo_id

#### Tech Debt
- [ ] Get rid of hardcoded plugin-images and make use of image_ref from the plugin_infos. 
       Requires: # to be done first.

#### UX Improvements
- [ ] Smart Expand 
    - [ ] Do not expand anything if all config repos are green
    - [ ] If a user creates a new config repo, expand that config repo (only for the current page)
    - [ ] Expand a config repo, if it has errors

- [ ] Smart Highlights/Indicators
    - [ ] Indicator for config repo never parsed
    - [ ]  Indicator for config repo MDU in progress
    - [ ]  Indicator for latest known commit is bad
    - [ ] Highlight config repo if it has errors

**Comment by GaneshSPatil** [comment]
Open question:
1.  Can we introduce config repo API v2, instead of creating an internal API?
    IMO, this information is necessary and it can be exposed using a public API.

**Comment by arvindsv** [comment]
@GaneshSPatil It looks good to me. I'd add that, upon adding a new repo, it should immedately be added to the queue to check for pipelines, rather than waiting a minute. I don't think that happens today.

We should also order this list (in this issue) in order of importance.

**Comment by GaneshSPatil** [comment]
#### Config Repo SPA Changes:

* No need of PluginID in the row header. Plugin Icon is explicit.

* Add good material revision and comment in the plugin header. In case of git, it will be short-commit-id and commit message.

* Improved status reporting for the state of the config repos. I personally find the current config-repo indicators a bit confusing, there is a red exclamation mark, and a brown.
  Here is the status symbols we need on the config repo spa, based on the config-repo revision validation state:
  - Never Parsed (unknown)
  - Last parsed commit is good (all green -- success)
  - last parsed commit (being the only parsed commit) is bad (all failed -- error)
  - last parsed commit is bad, but the previous commit was good (latest failed but previously green -- error with extra indication)

* Show Error messages as errors not as warnings.

* show information about the good modification (only if there is a good modification).
  - username + email
  - revision
  - comment
  - modified_time

* Show latest parsed modification (only if there are errors). Also show some relation between error and modification, as the error happened due to that specific revision.
  - username + email
  - revision
  - comment
  - modified_time

* When the latest modification is broken, But previous modification was good. Explicitly show that the (pipeline & environment) configurations are fetched/used from the previous modification and show that the latest modification has some errors.

**Comment by arvindsv** [comment]
Looks good! If the latest modification is bad, then if we have an "Info" popup or something, we should tell them that this repo will fail, upon startup.

**Comment by maheshp** [comment]
@GaneshSPatil I had few thoughts,

1. In cases where users have significant number of ConfigRepos how do we make it easy to identify/lookup for a specific ConfigRepo. 
2. Should we consider showing the material url in the non-expanded view. I am just wondering how useful would it be to show ConfigRepo id and other details of the modification without the material information. It is most likely users would not be able to tie an id to a ConfigRepo.
3. IMO, the modification details are taking too much space once expanded. I don't see a need for the key, probably we should consider keeping it short.

**Comment by kierarad** [comment]
@GaneshSPatil I think I mentioned this before but I still think the refresh icon and tooltip are ambiguous. What if we switched the tooltip to say "schedule material update" or "force material update" or "parse latest revision" instead of saying "refresh"

**Comment by GaneshSPatil** [comment]
> @GaneshSPatil I think I mentioned this before but I still think the refresh icon and tooltip are ambiguous. What if we switched the tooltip to say "schedule material update" or "force material update" or "parse latest revision" instead of saying "refresh"

@kierarad -- Thanks for the feedback. We can change the tooltip to `Force Material Update`. 
And if required, we can add some description about what it will do.

**Comment by GaneshSPatil** [comment]
Updated Design:
![image](https://user-images.githubusercontent.com/15275847/51375320-8925a480-1b2b-11e9-84b7-f9fb29cc870b.png)


We might make further enhancement to:
* Fit expanded config-repo to screen. To show only the expanded config-repo in the current window,
* Ability to search a config repo, based on the config-repo id, material, revision.

**Comment by naveenbhaskar** [comment]
<img width="688" alt="image" src="https://user-images.githubusercontent.com/1627961/52031691-c33b7100-2543-11e9-9b4f-7e4d212062a5.png">

**Comment by vishaldevgire** [comment]
@naveenbhaskar Should `Last checked` detail be outside `Last known good commit currently being used` section? 

<img width="983" alt="screen shot 2019-02-06 at 4 15 21 pm" src="https://user-images.githubusercontent.com/24635164/52336547-36088880-2a2b-11e9-83fb-d69852984bb0.png">

As it is an information about when did we last check for updates and it's not related to `Good commit`.

It should be somewhere at the top of the expanded panel or may be on non-expanded header just before the buttons.

<img width="1333" alt="screen shot 2019-02-06 at 4 25 15 pm" src="https://user-images.githubusercontent.com/24635164/52336998-6b61a600-2a2c-11e9-826a-c76e8cbbe1d4.png">

any thoughts?

**Comment by vishaldevgire** [comment]
This is how the Config SPA looks like:

1. All passed (current commit and previous commit both parsed successfully)

![all_passed](https://user-images.githubusercontent.com/24635164/52337923-fc398100-2a2e-11e9-98d3-ca67678ad846.gif)

2. Never parsed successfully

![never_parsed](https://user-images.githubusercontent.com/24635164/52337983-25f2a800-2a2f-11e9-903b-cf954739f080.gif)

3. Latest commit failed to parse but older good commit exists

![passed_then_failed](https://user-images.githubusercontent.com/24635164/52338069-589ca080-2a2f-11e9-8069-5c8801b970de.gif)

4. Search

![search](https://user-images.githubusercontent.com/24635164/52338367-36efe900-2a30-11e9-897c-ceaa8de6a7d6.gif)

User can search by `config repo id`, `revision hash`, `material url`

Note that the first panel is always rendered expanded but for the simplicity i have collapsed it in above GIFs.

**Comment by vishaldevgire** [comment]
Open Question to all, please reply with your thoughts:

As you search on Config Repo SPA, only config repos matching to search string are kept rendered on screen, this acts as a feedback to the user. This works well when the all panels are collapsed.

![proof-search](https://user-images.githubusercontent.com/24635164/52405337-09b73f80-2af1-11e9-908e-10f7932d5f66.gif)

But since the first config repo panel is always expanded, this can create some confusion while searching. Let's say only first config repo matches with our search string, in this case the user will see no change in UI until they scroll down.

![open_question](https://user-images.githubusercontent.com/24635164/52405386-26ec0e00-2af1-11e9-9e7f-06e05efa20c4.gif)

To handle this, we can do couple of things:
 - Collapse all panels when user starts searching
OR
 - Render search result count, this will act as feedback

**Comment by arvindsv** [comment]
My vote is for collapsing.

**Comment by GaneshSPatil** [comment]
I too think collapsed would be better.
Though just was wondering why can't we do both?

Collapse all the results and render count somewhere? `Found '2' config repositories matching 'repo'`.?

**Comment by adityasood** [comment]
I too am of the opinion that we can do both

**Comment by vishaldevgire** [comment]
Changes so far:

![image](https://user-images.githubusercontent.com/24635164/52459560-f1e0c980-2b8b-11e9-8c63-0e4d47dfd9ca.png)

This change adds following to Config Repo SPA:
- Details about last good commit latest commit, config repo configurations
![image](https://user-images.githubusercontent.com/24635164/52459503-931b5000-2b8b-11e9-9edd-9399269a21ea.png)
   - Checkbox before good and latest revision shows they were parse successfully. A red cross icon is rendered if there was error parsing repo.

- Search Box to search config repos by their id, material-url, commit revision hash (both good and latest commits)
![search_in_action](https://user-images.githubusercontent.com/24635164/52460427-3e2e0880-2b90-11e9-8260-87bf0e9b9ac3.gif)

- Adds Plugin Id, Material URL, Latest commit comment, hash, username to config repo panel header
![image](https://user-images.githubusercontent.com/24635164/52459665-83e8d200-2b8c-11e9-81a8-eda8de23a2e3.png)

- A red border indicating error in parsing config repo
  - Error is rendered in latest commit details section if the config repo was parsed before
![image](https://user-images.githubusercontent.com/24635164/52459877-aa5b3d00-2b8d-11e9-96a4-ccdcd0afb86c.png)
  - Error is rendered as a flash message if the config repo was never parsed
![image](https://user-images.githubusercontent.com/24635164/52460335-bfd16680-2b8f-11e9-8321-9a6a2cfec3d0.png)

- Added a spinner to panel header indicate config repo material update is in progress
![in_progress_update](https://user-images.githubusercontent.com/24635164/52460187-24d88c80-2b8f-11e9-8b00-7d79a9981829.gif)

Things remaining:

1. Last checked at (Last time we processed config repo)
![image](https://user-images.githubusercontent.com/24635164/52460565-efcd3980-2b90-11e9-83b1-830f3023ba14.png)
   - Where should it be rendered? Proposed location (inside good commit details section) looks odd.
2. While searching, collapse all panels and also render a search result count.

**Comment by GaneshSPatil** [comment]
@gocd/committers -- Here is the list of things which are pending on the config repo:
- [ ] Styling fixes \cc: @naveenbhaskar 
- [ ] Smart expands - expand only on errors
- [ ] Config repo materials expose password in plain text.
- [ ] For some materials, the latest commit message is not visible. Refer `ketan-pr-upgrade` config repo on build.gocd.org

**Comment by arvindsv** [comment]
@GaneshSPatil That last one, I don't think is a problem. If you clone the git (well, gist) repo, you'll see that the latest commmit has no commit message.

**Comment by arvindsv** [comment]
We can probably hide "Last known good commit currently being used" if the "Latest commit in the repository" is the same.

**Comment by rajiesh** [comment]
@vishaldevgire  @adityasood From the list of things discussed on this issue 2 minor UI things are pending-

- Show `Last checked x minutes ago..` message
- Tool tips on `Latest commit ...` and `Last known good commit....` to indicate what they mean. 

If we are planning to do it in next release, please close this issue and create another for the same

**Comment by adityasood** [comment]
added the above two issues at https://github.com/gocd/gocd/issues/5946. The rest of this is verified.
