### ISSUE TITLE
Functional issues in pipeline export feature

### ISSUE THREAD

**Issue by rajiesh** [gocd/gocd#5688]
##### Issue Type

- Bug Report

##### Summary

This issue captures all the issues related to pipeline export, it can also include regression issues caused by the pipeline export related code changes. Please add the issue description as the task list below, more description to the issue can be provided in comments and its  link added to task list below,

##### Issues

- [x] On `go/admin/pipelines` page `move to` option to move pipelines across groups is missing. @ketan pointed out that [this](https://github.com/gocd/gocd/pull/5509/files#diff-28e552efa7cda9715ac6567d9ec79858L2054) css change could be the issue. This was test issue, Kiera fixed it by [this](https://github.com/gocd/ruby-functional-tests/pull/282) commit 

- [x] Currently group admins cannot export a pipeline, API return 403 response. Shouldn't group admins have access to export pipelines on the group they are admins? IMO group admins should have access to export pipelines from the group they are admins.

- [ ] Exported json has `timeout` at task level. Timeout is applicable only at the job level settings. Also Job timeout value for `Never` should be integer `0` not float `0.0`. However timeout at task level or the float value for job timeout does not affect the pipeline, pipeline still works as expected. Please refer to the json [here](https://github.com/gocd/gocd/issues/5688#issuecomment-452983983)

- [x] ~~Export as option is available for pipeline coming from config repo too. It doesn't cause any issue but doesn't make sense to have export feature for config repo pipelines. Screenshot [here](https://github.com/gocd/gocd/issues/5688#issuecomment-452985332).~~ After watching the demo video by Marques could see whats the intention behind providing export option for config repo pipelines, striking this point off

- [x] Pipeline export should list only plugins with export capabilities. More details [here](https://github.com/gocd/gocd/issues/5730)

**Comment by rajiesh** [comment]
A exported pipeline in JSON,

```
{
  "group": "defaultGroup",
  "name": "test-export",
  "label_template": "${COUNT}",
  "lock_behavior": "none",
  "environment_variables": [],
  "parameters": [],
  "materials": [
    {
      "url": "https://github.com/gocd/gocd",
      "branch": "master",
      "shallow_clone": true,
      "filter": {
        "ignore": [],
        "whitelist": []
      },
      "auto_update": true,
      "type": "git"
    }
  ],
  "stages": [
    {
      "name": "defaultStage",
      "fetch_materials": true,
      "never_cleanup_artifacts": false,
      "clean_working_directory": false,
      "approval": {
        "type": "success",
        "users": [],
        "roles": []
      },
      "environment_variables": [],
      "jobs": [
        {
          "name": "defaultJob",
          "environment_variables": [],
          "tabs": [],
          "resources": [],
          "artifacts": [],
          "properties": [],
          "run_instance_count": "0",
          "timeout": 0.0,
          "tasks": [
            {
              "command": "ls",
              "timeout": -1.0,
              "arguments": [],
              "run_if": "passed",
              "type": "exec"
            }
          ]
        }
      ]
    }
  ]
}
```

**Comment by marques-work** [comment]
> Also Job timeout value for `Never` should be integer `0` not float `0.0`.

@rajiesh FWIW, javascript (and thus JSON) does not distinguish between float and integer. It just has the notion of `Number`. That said, we can look into making it look nicer. I suspect this is why `run_instance_count` is the string `"0"`, but I'm mostly speculating on that. Don't take my word for it :)

**Comment by kierarad** [comment]
@rajiesh in regards to the timeout-  @marques-work and I dug deeper and this is actually caused during the deserialization on the plugin side. If/when we update the plugins to utilize the Config Repo Contract jars that @ibnc created (https://github.com/gocd/gocd/pull/5470) this should fix the issue.

**Comment by marques-work** [comment]
@rajiesh to elaborate a little more, the fundamental problem is this:

1. The JSON plugin receives a JSON dump of the pipeline structure.
2. The JSON plugin deserializes this into a `Map<String, Object>`. For the reasons I stated in my previous message, this will deserialize the timeout values into java `double` values.
3. In the JSON plugin, this `Map<String, Object>` is reserialized (twice actually, but I digress -- ask me later if you want to know why) and the pipeline export receives the content. The reserialization writes the timeout values in floating point format because, after all, they are `double` values now.

The CR Contract models that @ibnc wrote will solve the problem by fixing deserialization; Gson will now know the proper types of the values during deserialization so timeout values will never be unmarshalled to `double`s. That's really the most elegant solution to this. I don't think it makes sense to traverse the `Map<String, Object>` to fix specific keys, so let's wait until the CR Models are available and then push fixes to the plugins individually.

**Comment by marques-work** [comment]
@rajiesh Also, with regards to whether or not `Tasks` should have timeouts at all -- `ExecTask` does have a `timeout` attribute. Admittedly, it's probably not well-known (or perhaps used at all) because we don't expose this on the UI.

But there is an `@ConfigAttribute` annotation: for it

https://github.com/gocd/gocd/blob/179934b3edc3ac884ee6d24cb0723387e341a336/config/config-api/src/main/java/com/thoughtworks/go/config/ExecTask.java#L43-L44

@kierarad and I didn't dive too deeply to see if the value is used at all in the codebase, but we presume it's used somewhere. Even if not, it's allowable, and probably settable in the config XML. So, technically, it is valid for `timeout` to exist at the task level in the serialized `CRPipeline` tree. If we want to remove it because it's not useful, we should remove it from the codebase altogether, which is a bigger, wider discussion.

**Comment by arvindsv** [comment]
@maheshp @marques-work @kierarad We should track this, as we will need to finish this before releasing it. If it is in the release in Feb, then it might be ok - but we will have to slot in the work around moving to the CR models.

**Comment by rajiesh** [comment]
@kiera was verifying the pipeline export feature for group admins on the latest build - 19.1.0 (8417-bc5413918eb9c792352710a4b6b79c64cea4f439) - which has your commit - https://github.com/gocd/gocd/pull/5708 - still the pipeline export returned `403` for group admin

**Comment by arvindsv** [comment]
@rajiesh You need to add @kierarad

**Comment by rajiesh** [comment]
The third point in issues list [here](https://github.com/gocd/gocd/issues/5688#issue-397477376) will be moved to separate issue, so closing this issue as other 3 in the list are fixed and verified
