### ISSUE TITLE
Ability to start server in maintenance mode

### ISSUE THREAD

**Issue by GaneshSPatil** [gocd/gocd#5787]
##### Issue Type

- Feature proposal

##### Summary
Currently, we can only put GoCD server into maintenance mode, but can not start a server in the maintenance mode.

Upon Server startup, it will start building pipelines, assigning jobs to agents, performing MDUs, etc.

Imagine a situation where one has migrated a server from one instance to another. Even before we can verify if the new configurations are fine. GoCD will start building.

Add an ability to start GoCD server in maintenance mode using system property.

**Comment by GaneshSPatil** [comment]
#### Possible Solution:

To Start GoCD Server in the maintenance mode, we can introduce a boolean system a property (may be named `gocd.server.enable.maintenance.mode`). And based on the value, the GoCD Server will either start normally, or in the maintenance mode.

#### Tasks

- [ ] Introduce maintenance mode system property to start GoCD Server in the maintenance mode.
- [ ] Fix message on the maintenance mode to mention clearly that the server was started in the maintenance mode (instead of saying `user X updated the maintenance mode state`)
- [ ] Fix message on all page footer to mention clearly that the server was started in the maintenance mode (instead of saying `user X updated the maintenance mode state`)
- [ ] Update [docs](https://docs.gocd.org/20.8.0/advanced_usage/maintenance_mode.html) to mention about the ability to start the GoCD Server in the maintenance mode.
-  [ ] Add a functional spec to start the GoCD Server in the maintenance mode.

**Comment by GaneshSPatil** [comment]
@maheshp @kritika-singh3 @marques-work @gocd/committers -- Thoughts??

**Comment by kritika-singh3** [comment]
@GaneshSPatil Few thoughts:

1. How about `gocd.server.start.in.maintenance.mode` for the system property.
2. Suppose the server is started in maintenance mode. The admin/user verifies everything and disabled it via SPA/API. Now if the server is restarted - will it come up normally or in maintenance mode?
3. Should the config-repo fetch and parse happen if we start the server in maintenance mode?

**Comment by GaneshSPatil** [comment]
@kritika-singh3 --

> 1. How about `gocd.server.start.in.maintenance.mode` for the system property.

Sure. we can use this system property.

> 2. Suppose the server is started in maintenance mode. The admin/user verifies everything and disabled it via SPA/API. Now if the server is restarted - will it come up normally or in maintenance mode?

The GoCD Server will always start in the maintenance mode. It may be confusing for the end user if the subsequent re-starts starts the GoCD Server normally. 
May be we add a note about this on the docs?


> 3. Should the config-repo fetch and parse happen if we start the server in maintenance mode?

The current implementation does not allow fetching and parsing of the config repositories as it will result into updating the cruise-config.xml when in maintenance mode.

**Comment by kritika-singh3** [comment]
> The GoCD Server will always start in the maintenance mode. It may be confusing for the end user if the subsequent re-starts starts the GoCD Server normally (Even when the property is specified).
May be we add a note about this on the docs?

Yes please. 

> The current implementation does not allow fetching and parsing of the config repositories as it will result into updating the cruise-config.xml when in maintenance mode.

Taking this use-case
> Imagine a situation where one has migrated a server from one instance to another. Even before we can verify if the new configurations are fine. GoCD will start building.

Should we allow fetching of only config-repo once and parse the same, in case the property is set?

**Comment by maheshp** [comment]
@GaneshSPatil adding a System Property sounds ok to me. We just need to make sure that as part of the server start none of the operations supposed to be disabled in maintenance mode should be started.

**Comment by GaneshSPatil** [comment]
@kritika-singh3  --

> Should we allow fetching of only config-repo once and parse the same, in case the property is set?

I understand your use-case.
So, when the first time server is started in the maintenance mode, the config repositories will not be parsed, and the pipelines coming through config repositories will not be shown on the UI.

Though, allowing config-repositories to be parsed once can result into un-intended changes, such as, the commits during the restart will also be parsed.

Also, i am not sure if using the appropriate revision of the config repository is the problem of the maintenance mode. Maintenance mode just disables all GoCD sub-systems, and config-repo pipelines are not showing up is the side effect of such behavior.

There was a point brought up by the team (hope @arvindsv / @maheshp remembers) where, GoCD should have the ability to backup the config repositories too and should be able to restore to the same revision/config-version when the backup was taken. The above feature will parse the config repositories to the exact same revision/config-version, to the point where GoCD server was brought down.

**Comment by arvindsv** [comment]
Yes, I think the assumption was that the flyweights would continue to exist across restarts and that whatever is there will be used to show pipelines. I think that conversation was about a general restart (not maintenance mode), when GoCD doesn't show pipelines till a successful MDU for config repos.

**Comment by GaneshSPatil** [comment]
> Yes, I think the assumption was that the flyweights would continue to exist across restarts and that whatever is there will be used to show pipelines. I think that conversation was about a general restart (not maintenance mode), when GoCD doesn't show pipelines till a successful MDU for config repos.

@arvindsv - Yes, Thank you for the explanation!

NOTE: The following comment is applicable only if the above feature is implemented. As of GoCD Release `v20.7.0`, this feature is not implemented.

Considering the fact that the flyweight folder is present and the server is started in maintenance mode, the pipelines will show up from the last checked-out config repositories.

For a clean restore of the GoCD backup and starting the server in maintenance mode, As there would be no flyweight folder, no pipelines from config repositories will show up.

---

So, without the ability to use the checked-out code of config repositories from flyweight folder; When the GoCD Server is started in the maintenance mode, no config repository pipelines will be visible.

\cc: @kritika-singh3 @arvindsv @maheshp @marques-work

**Comment by maheshp** [comment]
Done as part of https://github.com/gocd/gocd/pull/8593
