### ISSUE TITLE
Update how GoCD fetches git materials

### ISSUE THREAD

**Issue by arvindsv** [gocd/gocd#5856]
##### Issue Type

- Feature enhancement

##### Summary

It's been a while. `git` has changed over time and provides more features. This is a placeholder to take a look at the git material and see what can be changed. For instance, there's usage of `git submodule foreach` and reading the `.gitconfig`, etc. which might be replaced with `git submodule sync`.

When doing this, we should also consider other issues brought up around git, such as:
  - [x] Shallow clone doesn't apply to submodules: https://github.com/gocd/gocd/issues/2123
  - [ ] ~~Use the `--jobs` flag when updating submodules to parallelize the operation~~
  - [ ] Maybe look at whether `GIT_SSH_COMMAND` can be incorporated?
  - [x] Possibly do a `git clean -dffx`? [Might be a breaking change. Be careful]
  - [x] GoCD fails to update git submodules: https://github.com/gocd/gocd/issues/3635
  - [ ] ~~Skip git gc, resetting, cleaning if clean working directory is used: https://github.com/gocd/gocd/issues/2124~~
  - [x] Check connection should check if branch name is valid: https://github.com/gocd/gocd/issues/2093
  - [x] Add git material fails, with color options in the .gitconfig file: https://github.com/gocd/gocd/issues/326

Issue opened after a conversation with @GaneshSPatil.

**Comment by ibnc** [comment]
@kierarad or @arvindsv would either of you be up for giving this PR one last review, and then merging if everything looks good?

**Comment by akshaydewan** [comment]
Here's the current process that happens when we reset the working directory before running a job: (`GitCommand.resetWorkingDir`)

``

**Comment by akshaydewan** [comment]
Another possible optimization that we can do while implementing **Shallow clone doesn't apply to submodules** - if we run `git clone` with additional args `--recurse-submodules` and `--shallow-submodules`, then we can potentially save time by not resetting the working directory as described in #2124 , because re-initializing submodules would be immediately after cloning is not needed and takes up time.

**Comment by arvindsv** [comment]
I wonder if it makes sense to say that if you use submodules, you'll need version X. If there is no `.gitmodules`, maybe we don't need to run those commands at all?

It would be nice to not force a new version unnecessarily. Having said all that 2.13 is already considered "old". So, it wouldn't be wrong for us to drop support for others.

**Comment by akshaydewan** [comment]
Here's what I found in Git's release notes:

1.7.4
 * "git submodule sync" updates metainformation for all submodules,
   not just the ones that have been checked out.
* "git fetch" learned the "--recurse-submodules" option.


1.8.1
 * "git submodule sync" learned the "--recursive" option.


1.8.3
* There was no Porcelain way to say "I no longer am interested in
   this submodule", once you express your interest in a submodule with
   "submodule init".  "submodule deinit" is the way to do so.


2.9.0
* "git clone" learned the "--shallow-submodules" option.


2.14.0
* "git clean -d" used to clean directories that has ignored files,
   even though the command should not lose ignored ones without "-x".


> I wonder if it makes sense to say that if you use submodules, you'll need version X.

I guess all the commands should work for anyone using git version over 2.13

**Comment by arvindsv** [comment]
To me, that sounds ok.

**Comment by akshaydewan** [comment]
@arvindsv If we set the `GIT_SSH_COMMAND` environment variable on the agent machine, it is picked up and used. It's probably a bit inconvenient because a user would have to set it up while provisioning an agent, but it works. Did you have something specific in mind for the UX around this?

**Comment by arvindsv** [comment]
@akshaydewan Yes. There's a lot of discussion in #951 as well. My ideal, for a user, would be:

1. At a material level, there's an option to provide an SSH private key securely. Upcoming support for secrets will be allowed too (specifying it as: `#{SECRET:[abc][def]}` instead of a private key).

2. GoCD sees that an SSH key is defined and does the right thing, setting `GIT_SSH_COMMAND` properly. Shouldn't forget Windows.

3. Once done, it cleans up any keys left behind on the filesystem. Before any tasks start.

That's what I would expect ideally. Happy to be corrected / have a discussion.

**Comment by ketan** [comment]
I have some (working) code to show around `GIT_SSH_COMMAND` and passing in an SSH key that just works.

**Comment by akshaydewan** [comment]
I tried using `--jobs` in a repo with 3 submodules and didn't notice any difference in performance:

```
git submodule update --init --jobs=3  14.70s user 4.57s system 39% cpu 49.004 total
git submodule update --init           14.70s user 4.53s system 44% cpu 43.105 total
```

I'd avoid adding more complexity if we aren't gaining anything from it.

**Comment by adityasood** [comment]
verified through test pipeline run (https://build.gocd.org/go/pipelines/git-tests/46/test/1)
