### ISSUE TITLE
Migrate PluginInfo API from Rails to Spark

### ISSUE THREAD

**Issue by dhanasp** [gocd/gocd#6007]
##### Issue Type

- Feature enhancement

##### Summary

Migrate `PluginInfos` API from rails to spark

- [x] Implement [`Index`](https://github.com/gocd/gocd/issues/6007#issuecomment-477460601) API endpoint with basic plugin info (links, id, plugin_file_location, bundled_plugin)
- [x] Implement [`show`](https://github.com/gocd/gocd/issues/6007#issuecomment-477499487) API endpoint with basic plugin info(links, id, plugin_file_location, bundled_plugin)
- [x] Add `status details` in index and show API response
- [x] Add `about section` in index and show API response
- [x] Add [`extention details`](https://github.com/gocd/gocd/issues/6007#issuecomment-477460124) in index and show API response

**Comment by kierarad** [comment]
@dhanasp just to document @vrushaliwaykole reached out to me and we talked about this on slack, but the capabilities need to be added to the config repos extension of the plugin infos API. It would be great for that to be included as part of this. 

Let me know if you are up for adding this to the scope of what you are doing. Otherwise let me know and I will add it once you've completed the migration so that I can fix #5730

**Comment by dhanasp** [comment]
@kierarad, I and @vrushaliwaykole are working on this. We will complete this first and let you know.

**Comment by dhanasp** [comment]
Need to add extension info in plugin info API response
Following are the supported extensions

- [ ] `authorization` - type, auth_config_settings, role_settings, capabilities(can_search, supported_auth_type, can_authorize)

- [ ] `scm` - type, display_name, scm_settings

- [ ] `configrepo` - type, plugin_settings

- [ ] `elastic-agent` - type, plugin_settings, profile_settings, capabilities(supports_status_report, supports_agent_status_report)

- [ ] `task` - type, display_name, task_settings

- [ ] `package-repo` - type, package_settings, repository_settings

- [ ] `notification`- type, plugin_settings

- [ ] `analytics` - type, plugin_settings, capabilities(list of objects with info id, title, type)

**Comment by dhanasp** [comment]
As part of Index API, Need to handle following scenarios

- [ ] Load all valid plugin infos 
- [ ]  exclude plugins with unsupported extensions
- [ ]  when `include_bad` parameter is passed, all invalid plugins should be included in the list
- [ ]  when `type` (extension type) is passed as parameter, list all plugins that uses extension of type specified

**Comment by dhanasp** [comment]
##### Issue Type

- Feature enhancement

##### Summary
As part of `show` endpoint, need to handle the following scenarios -
- [ ] When the plugin is valid and present in the system, send plugin info. 
Parameters in plugin info response
```
 Links - Links for `self`, `doc`, `find`, `image`(only if present)
    id - plugin id
    status: 
        - `state` of plugin
        - `messages` (only if plugin is invalid)
    plugin_file_location
    bundled_plugin
    about
        - name
        - version
        - target_go_version
        - description
        - target_operating_systems
        - vendor object with `name` and `url`
    extensions
        - information for extensions `authorization`, `scm`, `configrepo`, 
         `elastic-agent`, `task`, `package-repo`, `notification`, `analytics` (only if plugin is valid)
```
- [x] When the plugin is invalid and present in the system, send the messages as well in the response as part of status
- [x]  when the plugin is not present in the system, send `not found` error response
- [ ]  When the plugin is using an unsupported extension, send `not found` error response

**Comment by rajiesh** [comment]
Verified on 19.3.0 (8959-259d1f79e361875995072e5c1fcc9cbda7ccc600)
