### ISSUE TITLE
Ability to configure stage to only allow manual trigger on success of previous stage

### ISSUE THREAD

**Issue by granddesigntech** [gocd/gocd#6294]
##### Issue Type
- Feature enhancement

##### Summary
I have stages in my pipeline that require resource with specific role to manually execute as a way of approval management.

However, manual trigger does not stop the manual trigger if the previous stage failed. This means that potential for human error is not alleviated by this automation whic is of course a major selling point to our stakeholders.

We would like to have the manual trigger configuration allow to specify whether manual trigger should be possible only upon success of previous stage or regardless of previous stage result.

##### Environment
NA - not a bug

###### Basic environment details
NA - not a bug

###### Additional Environment Details
NA - not a bug

##### Steps to Reproduce
1. create pipeline with stage 1 hardcoded to fail
2. add stage 2
3. set stage 2 Type to Manual 
4. run pipeline

##### Expected Results
stage 2 is not manually triggerable

##### Actual Results
stage 2 is manually triggerable

##### Possible Fix
This feature enhancement request

##### Log snippets
NA - Not a bug

##### Code snippets/Screenshots
NA - Not a bug

##### Any other info
NA - Not a bug

**Comment by maheshp** [comment]
With the manual trigger I am assuming the users would be taking an informed decision before triggering the stage. 

Instead of introducing a configuration, does it make sense to change the UX by taking a confirmation before actually triggering the stage. IMO adding a configuration for this would lead to a configuration proliferation.

**Comment by arvindsv** [comment]
I thought about that and then realized that it already has a confirmation. So, the original request then is a specific flag to turn it off. To disallow forcing it.

**Comment by maheshp** [comment]
> I thought about that and then realized that it already has a confirmation. 

Yeah, I dint realize that.

**Comment by granddesigntech** [comment]
> With the manual trigger I am assuming the users would be taking an informed decision before triggering the stage.
This is for an enterprise customer in the finance industry and they have security requirements that are not legal to leave up to the good judgment of their personnel.

A little more proliferation of configuration enabling tighter security controls wouldn't go astray to be honest.

**Comment by maheshp** [comment]
> A little more proliferation of configuration enabling tighter security controls wouldn't go astray to be honest.

@granddesigntech fair enough! I understand your requirements better now.

**Comment by kritika-singh3** [comment]
Introducing additional check if the approval type for stage run is `manual` by adding config attribute/tag, which when configured with `success`, will allow to manually trigger only on a successful run of the previous stage.

Currently, cruise-config.xml looks like:

```xml
<approval type="manual" />
```

which will get updated to: 

1. Updating `manual` and `success` to subtags

```xml
<approval>
  <manual allow="success" /> #or
  <manual allow="any" />  #or
  <success />
</approval>  
```
2. Adding `allow` subtag to `approval` tag 

```xml
<approval type="manual">
  <allow on="success" /> #or
  <allow on="any" />  #default
</approval>  
```
@gocd/godev  WDYT?

**Comment by arvindsv** [comment]
I feel like something like: `<approval type="manual" allowOnlyOnSuccess="true" />` has the advantage of keeping all existing configs valid and any scripts like gomatic working.

**Comment by kritika-singh3** [comment]
In the case of `type="success"`, `allowOnlyOnSuccess` will make no sense, wouldn't it?

**Comment by arvindsv** [comment]
Correct. It wouldn't. We'd need to set that to `false`, which will be the the default and so, it'll remove it from the config, is what I was thinking.

**Comment by kritika-singh3** [comment]
Adding `allowOnlyOnSuccess` attribute to `approval` tag which will be utilized if `type` is set to `manual`.

### TODO
 - [x] Add support for the attribute in `cruise-config.xsd` 
 - [x] Cruise config migration
 - [x] UI Changes
      - [x] Add checkbox for `allowOnlyOnSuccess` attribute on new stage add popup and edit stage 
              settings
      - [x] Disable manual trigger button along with tooltip content
 - [ ] Add support for the attribute in config repo
 - [ ] Update the config repo plugins
      - [ ] JSON plugin
      - [ ] YAML
      - [ ] Groovy
 - [ ] Bump up the Pipeline Config API to v8
 - [ ] Bump up the config repo message handler to v3

**Comment by kritika-singh3** [comment]
@arvindsv @gocd/godev,

Thoughts about:
 - which is preferred `runOnlyOnSuccess` or `allowOnlyOnSuccess`?
 - should we utilize this attribute for `success` approval as well? 
    Meaning, in case a stage fails, we can force trigger the next stage. Should we use this trigger for 
    that behavior as well instead of just  `manual` triggers?

**Comment by arvindsv** [comment]
> Meaning, in case a stage fails, we can force trigger the next stage. Should we use this trigger for
that behavior as well instead of just manual triggers?

Yes, I think so.

> which is preferred runOnlyOnSuccess or allowOnlyOnSuccess?

Since this is mostly about a user-intervention, I felt `allow` made sense.

**Comment by rajiesh** [comment]
Verified on 19.8.0 (9912-33898b3adaf72cedea1604882d3554fd586571a8)

**Comment by TorstenE** [comment]
Is there also the possibility
add the "approval" tag with gomatic (Python) ?

**Comment by arvindsv** [comment]
I don't think gomatic is maintained, but you should be able to set this via the APIs (https://api.gocd.org/current/#the-approval-object) and via pipelines as code (https://docs.gocd.org/current/advanced_usage/pipelines_as_code.html).
