### ISSUE TITLE
Support for username/password attribute in git and hg(and branch) material

### ISSUE THREAD

**Issue by bdpiparva** [gocd/gocd#6298]
### Issue Type
- Feature proposal
- Feature enhancement

### Issue
Git and Hg material does not have a username and password attributes on it, hence the user has configured the material with credentials URL. Supporting username and password attributes can provide additional benefits of storing a password as an encrypted value rather than a plain text in URL.

#### Support for username and password attribute for git and hg

Going forward Git and Mercurial will have support to configure credentials as username and password attributes.  We are encouraging users to migrate the credentials from URL to attributes.

> Old git/hg material config

```xml
<git url="https://username:password@github.com" />
<hg url="https://username:password@domain.com" />
```

> New way of defining git material config

```xml
<git url="https://github.com" username="username" password="password" />
<hg url="https://domain.com" username="username" password="password"/>
```

#### Support for branch attribute on hg

Currently, hg material branch is defined in the URL itself e.g `https://username:password@domain.com##feature` where `feature` is the branch name. 
The new way of defining branch in hg is - 

```xml
<hg url="https://domain.com" username="username" password="password" branch="feature" />
``` 

### Validation

- Credentials can be provided either in URL or as attributes for hg and git material. Specifying in both will result in a validation error.
- Branch in hg material URL can be configured either in URL or as an attribute. Specifying in both will result in a validation error.

### Fingerprint

- Git: No change in fingerprint generation
- Hg: Branch attribute will be considered in fingerprint generation if configured.

### APIs
Affected APIs because of this change are `config-repo-v1` and `pipeline-config-v6`, and it will be updated to support the username, password, and branch(for hg) attributes.

#### Config repo v1

- Nothing is changed

#### Config repo v2

<details>
	<summary>Create: Supports credentails in url</summary>

```bash
curl 'http://ci.example.com/go/api/admin/config_repos' \
  -u 'username:password' \
  -H 'Accept:application/vnd.go.cd.v2+json' \
  -H 'Content-Type:application/json' \
  -X POST -d '{
    "id": "repo-2",
    "plugin_id": "json.config.plugin",
    "material": {
      "type": "git",
      "attributes": {
        "url": "https://bob:pass@github.com/config-repo/gocd-json-config-example2.git",
        "branch": "master",
        "auto_update": true
      }
    },
    "configuration": [{"key": "pattern","value": "*.myextension"}]
  }'
```
</details>

<details>
	<summary>Create: Supports credentails as attributes</summary>

```bash
curl 'http://ci.example.com/go/api/admin/config_repos' \
  -u 'username:password' \
  -H 'Accept:application/vnd.go.cd.v2+json' \
  -H 'Content-Type:application/json' \
  -X POST -d '{
    "id": "repo-2",
    "plugin_id": "json.config.plugin",
    "material": {
      "type": "git",
      "attributes": {
        "url": "https://github.com/config-repo/gocd-json-config-example2.git",
        "branch": "master",
        "auto_update": true,
        "username"   : "bob",
        "password"   : "pass"
      }
    },
    "configuration": [{"key": "pattern","value": "*.myextension"}]
  }'
```
</details>

<details>
	<summary>Create: Supports branch as attribute in Hg</summary>

```bash
curl 'http://ci.example.com/go/api/admin/config_repos' \
  -u 'username:password' \
  -H 'Accept:application/vnd.go.cd.v2+json' \
  -H 'Content-Type:application/json' \
  -X POST -d '{
    "id": "repo-2",
    "plugin_id": "json.config.plugin",
    "material": {
      "type": "hg",
      "attributes": {
        "url": "https://github.com/config-repo/gocd-json-config-example2.git",
        "branch": "master",
        "auto_update": true,
        "username"   : "bob",
        "password"   : "pass",
        "branch"     : "feature"
      }
    },
    "configuration": [{"key": "pattern","value": "*.myextension"}]
  }'
```
</details>

#### Pipeline config v6

- Nothing is changed

#### Pipeline config v7

<details>
	<summary>Create: Supports credentails in url</summary>

```bash
curl -X POST 'http://localhost:8153/go/api/admin/pipelines' \
-u 'admin:badger' \
-H 'Accept: application/vnd.go.cd.v7+json' \
-H 'Content-Type: application/json' \
-d '{ 
		"group": "first",
		"pipeline": {
			...
			"materials" : [ {
		    "type" : "hg",
		    "attributes" : {
		      "url" : "https://bob:password@foo.com##feature",
		      "destination" : null,
		      "filter" : null,
		      "invert_filter" : false,
		      "name" : null,
		      "auto_update" : true
		    }
	  	}]
		}
	}'

```
</details>

<details>
	<summary>Create: Supports credentails as attributes</summary>
	
```bash
curl -X POST 'http://localhost:8153/go/api/admin/pipelines' \
-u 'admin:badger' \
-H 'Accept: application/vnd.go.cd.v7+json' \
-H 'Content-Type: application/json' \
-d '{ 
		"group": "first",
		"pipeline": {
			...
			"materials" : [ {
		    "type" : "hg",
		    "attributes" : {
		      "url" : "https://foo.com##feature",
		      "destination" : null,
		      "filter" : null,
		      "invert_filter" : false,
		      "name" : null,
		      "auto_update" : true,
		      "username" : "bob",
		      "password" : "pass"
		    }
	  	}]
		}
	}'

```
</details>

<details>
	<summary>Create: Supports branch as attribute</summary>
	
```bash
curl -X POST 'http://localhost:8153/go/api/admin/pipelines' \
-u 'admin:badger' \
-H 'Accept: application/vnd.go.cd.v7+json' \
-H 'Content-Type: application/json' \
-d '{ 
		"group": "first",
		"pipeline": {
			...
			"materials" : [ {
		    "type" : "hg",
		    "attributes" : {
		      "url" : "https://foo.com",
		      "destination" : null,
		      "filter" : null,
		      "invert_filter" : false,
		      "name" : null,
		      "auto_update" : true,
		      "username" : "bob",
		      "password" : "pass",
		      "branch"   : "feature"
		    }
	  	}]
		}
	}'

```
</details>

<details>
	<summary>Create: credentials validation</summary>

```bash
curl -X POST 'http://localhost:8153/go/api/admin/pipelines' \
-u 'admin:badger' \
-H 'Accept: application/vnd.go.cd.v7+json' \
-H 'Content-Type: application/json' \
-d '{ 
		"group": "first",
		"pipeline": {
			...
			"materials" : [ {
		    "type" : "hg",
		    "attributes" : {
		      "url" : "https://bob:password@foo.com##feature",
		      "destination" : null,
		      "filter" : null,
		      "invert_filter" : false,
		      "name" : null,
		      "auto_update" : true,
		      "username" : "bob",
		      "password" : "pass"
		    }
	  	}]
		}
	}'
```

The above request will fail with 422 -

```json
{
	...
	"materials": [
  {
    "errors": {
      "url": [
        "Ambiguous credentials, must be provided either in URL or as attributes."
      ]
    },
    "type": "hg",
    "attributes": {
      "url": "https://bob:password@foo.com##feature",
      "destination": null,
      "filter": null,
      "invert_filter": false,
      "name": null,
      "auto_update": true,
      "username": "bob",
      "encrypted_password": "AES:nBbE8PKR8IityrMhxXC1YQ==:quEAzIKPx3AsHSpNE3Cw5g=="
    }
  }]
	...
 }

```
</details>

### Config repo
 Will be updated soon

### TODO
- [x] Add support for username and password attributes in git and hg materials
- [x] Add support for branch attribute in hg
- [x] Validate Git and Hg Material
- [x] Check connection for git and hg
- [x] Verify/update config repo contract
- [ ] Check if config repo plugins need an update 
- UI
    - [x] Create a new pipeline(#6305)
    - [x] Pipeline edit
    - [x] Config repo spa(#6306)
- [x] Bump up config repo API to v2 and pipeline config to v7
- [ ] Update release notes

**Comment by bdpiparva** [comment]
@adityasood - UI is updated for edit pipeline config view to have a username and password attributes for git and hg both, and branch name on hg material. As of now, I am not updating the create new pipeline flow cus there is some work going on around simplifying pipeline creation flow. In the near future, it will become the default view to create a new pipeline.

**Comment by adityasood** [comment]
@bdpiparva regarding the credentials in the create new pipeline flow, I am just wondering if this change will be visible if we don’t bring it in that view. My concerns are

1. Until the new view, this change might be overlooked for users creating new pipeline and hence the practice of using attributes for credentials might not be achieved

2. Once the material is configured (this is even true for existing materials), users might not visit the material configuration to edit and change the credentials from URL to attributes.

**Comment by bdpiparva** [comment]
> Until the new view, this change might be overlooked for users creating new pipeline and hence the practice of using attributes for credentials might not be achieved

Agreed, If the new will is not finished before the release I will put it in existing create pipeline flow.

**Comment by adityasood** [comment]
Test scenarios:
 The following validations were done

1. CRUD on the Config-repo v1, config repo v2, pipeline config v6 and Pipeline config v7. This included both a happy path and negative test cases.

2. UI flow was validated with various URL's, test connection validation and ambiguous attribute validations.
   a.) Create a new pipeline with material as git: URL formats tried with variations for negative test cases
          i) https://githuburl/abc.git
          ii) https://<username>:pwd@githuburl/abc.git
          iii) https://githuburl/abc.git username,password and branch as attributes
          iv) https://<username>:pwd@githuburl/abc.git and branch as attribute
          v) git@bitbucket.org:user/git-functional-tests.git
          vi) https://<username>:pwd@githuburl/abc.git and branch as attributes
          vii) https://#{git-username}:pwd@bitbucket.org/abc.git with #{git-branch} as attribute
          viii) https://githuburl/abc.git with username and branch as parameterized attributes and password attribute

   b.) These materials were updated in update material UI
   c.) Create a new pipeline with material as hg: URL formats tried with variations for negative test cases
          i) https://soodadi@bitbucket.org/soodadi/mercurial-repo
          iii) https://bitbucket.org/soodadi/mercurial-repo username,password and branch as attributes
          iii) https://<username>:pwd@bitbucket.org/soodadi/mercurial-repo and branch as attribute
          iv) ssh://hg@bitbucket.org/soodadi/mercurial-repo##test-hg
          v) ssh://hg@bitbucket.org/soodadi/mercurial-repo branch as attribute.
          vi) https://soodadi@bitbucket.org/soodadi/mercurial-repo##branch
         vii) ssh://bitbucket.org/soodadi/mercurial-repo and branch and user as attribute
         viii) https://##{hg-username}:pwd@bitbucket.org/soodadi/mercurial-repo###{hg-branch}
    d.) These materials were updated in update material UI

3. Config repositories configurations through UI was validated with test connection validation and ambiguous attribute validations.

4. Material polling was turned off to assure for different fingerprint for URL's. For e.g

URL1: https://githuburl/abc.git username, password, and branch as attributes
URL2: https://#{git-username}:pwd@githuburl/abc.git with branch as attributes

The above URLs will have different fingerprints and hence polling off on one should not affect the others.

5. Fingerprints generation was verified for different combinations of URL's
6. Clone operations were verified for different operations
7. Upgrade scenario was verified and fingerprints were checked before/after upgrades
8. Sanity was done with SVN materials
9. SSH based URL's were verified


To do:

[ ] Functional Tests

**Comment by arvindsv** [comment]
@adityasood If I'm on 19.3 and have some materials and update to 19.4, then no new flyweight directories should be created in the checkouts dir on the server. Right? Do you mind keeping an eye out on this scenario, in case you haven't? Unless that's _exactly_ what you mean by: "Upgrade scenario was verified and fingerprints were checked before/after upgrades" :)

**Comment by adityasood** [comment]
@arvindsv the upgrade was tested for precisely the same scenario as you have mentioned.

**Comment by maheshp** [comment]
@adityasood listing out few more scenarios,
1. Password should be masked wherever the URL is displayed, e.g logs, server health messages, UI where we should material and modifications.
2. Post upgrade no new material instances should be created unless a new material is added.
3. Post upgrade pipelines should not be triggered unless MDU finds new modifications.
4. Good to verify Fan-in.

**Comment by adityasood** [comment]
Verified: 19.4.0-9139.
