### ISSUE TITLE
Option to allow plugin users to login without explicitly being added at each plugin level

### ISSUE THREAD

**Issue by GaneshSPatil** [gocd/gocd#6571]
##### Issue Type

- Feature enhancement

##### Summary

Currently, User Management section on the Server Configuration Page specifies an option to allow users to login via plugin into GoCD, even if they haven't been explicitly added to GoCD.

This is a global setting for all the plugins.
If turned on, all the users from all the auth-configs are allowed to log-in into the system without being explicitly added.
If turned off, no user is allowed to login into the system, without being explicitly added.

Imagine the following scenario,
I have 2 following auth configs:
1. `file-based-auth`: where I have added all the users from my team.
2. `github-auth`: where I have configured public GitHub for all organizations.

Now, with this setup, I want to allow all the users from `file-based-auth` and selected users from `github-auth`.
Turning on the global setting isn't a solution as it will allow all the users from GitHub to login into the system.
Turning off the global setting isn't too a solution as it will require administrators to manually go through all users list (from passwd file) and add them into the system explicitly.

##### Possible Solution
Allowing this flag (`allow users to login via plugin into GoCD, even if they haven't been explicitly added to GoCD`) to be configurable per auth config will provide more control. And administrators can choose to toggle it on or off based on the requirement.

#### Task Checklist
 - [x] Add config migration to migrate allowOnlyKnownUsersToLogin attribute from server to each auth config. (https://github.com/gocd/gocd/pull/7178)
 - [x] Remove old rails based server configuration page. (https://github.com/gocd/gocd/pull/7188)
 - [x] Introduce auth config API v2 to support allowOnlyKnownUsersToLogin. (https://github.com/gocd/gocd/pull/6605)
 - [x] Fix auth config SPA to support allowOnlyKnownUsersToLogin. (https://github.com/gocd/gocd/pull/7205)
 - [x] Document allowOnlyKnownUsersToLogin at auth config on docs.gocd.org
 - [x] Document Auth Config Api v2

**Comment by GaneshSPatil** [comment]
@gocd/committers -- Thoughts??

**Comment by bdpiparva** [comment]
@GaneshSPatil - I agree with the proposed solution. The flag should be provided for each plugin. For organization, an admin may want to add the LDAP user without any manual intervention but for the plugins like GitHub, they may want to disable it.

PS: if we decide to do it, we have to retain the existing selection for the current flag and apply it for all the installed plugin auth config.

**Comment by arvindsv** [comment]
Ok, makes sense. If there's a chance to incorporate https://github.com/gocd/gocd/issues/6344 while thinking about this, we should. They're different, yet somewhat related.

**Comment by maheshp** [comment]
While this makes sense, my preference would be to not implement this as of now till we have more use cases for doing this. 

I am wondering if users can disable `allowOnlyKnownUsersToLogin` and control which users can login using the `AllowedOrganizations` configuration using the Github Auth Plugin or the `SearchBases` for LDAP plugin.

**Comment by GaneshSPatil** [comment]
@maheshp --

> I am wondering if users can disable allowOnlyKnownUsersToLogin and control which users can login using the AllowedOrganizations configuration using the Github Auth Plugin or the SearchBases for LDAP plugin.

I agree with you on this.

> While this makes sense, my preference would be to not implement this as of now till we have more use cases for doing this.

Hmm, the main reason for considering this feature was to rewrite the server-configuration page.
On the server configuration page, users are allowed to set the `allowOnlyKnownUsersToLogin` flag by enabling `allow users to login via plugin into GoCD, even if they haven't been explicitly added to GoCD` checkbox. This value is set as an attribute on the `security` tag in the `cruise-config.xml`.

If we want to rewrite the server configuration page as a SPA, we would need an API endpoint to allow toggling this value. 
If we choose not to do this feature now, we would need to introduce an API to allow toggling `allowOnlyKnownUsersToLogin` field.

**Comment by adityasood** [comment]
> I am wondering if users can disable `allowOnlyKnownUsersToLogin` and control which users can login using the `AllowedOrganizations` configuration using the Github Auth Plugin or the `SearchBases` for LDAP plugin.

While this might allow for finer control for each auth-config, it also would imply that the configuration on LDAP server or GitHub organization would have to be made accordingly.

It would still have some of the issues such as #6344, until the user is explicitly removed from AD group.

IMO while authorization or authentication might happen at the plugin, GoCD should still have a way to have a set of known users and a way to restrict the usage for a server instance only for them.

I like the idea of bringing this to each auth-config and removing it from global settings. This way users can have an AD group where anyone can log in and another AD group with only known users allowed.

**Comment by maheshp** [comment]
> It would still have some of the issues such as #6344, until the user is explicitly removed from AD group.

I don't think adding `allowOnlyKnownUsersToLogin` at each auth-config level would fix #6334.

**Comment by arvindsv** [comment]
Yes. #6344 won't be fixed by adding this. Will need to do what's mentioned there, if fixing that.

**Comment by GaneshSPatil** [comment]
Done as part of GoCD release `v19.11.0`
Closing...
