### ISSUE TITLE
Allow associating job with the elastic profile from the elastic agents SPA

### ISSUE THREAD

**Issue by bdpiparva** [gocd/gocd#6720]
##### Issue Type
- Feature proposal

##### Summary

Allow association jobs the elastic profile from the elastic agent's SPA. See the attached screenshot for more details

![Screenshot 2019-08-06 at 1 33 30 PM](https://user-images.githubusercontent.com/7871209/62522595-9ef08200-b84f-11e9-9d75-bc5195782c21.png)

---

#### TODO

- [ ] Allow user to search for a pipeline
- [ ] User should be able to associate all jobs within the pipeline to the elastic profile
- [ ] User should be able to associate all jobs within the stage to the elastic profile
- [ ] Should display the already linked jobs with other elastic profile or resources in a disabled state with appropriate help text

Q. Should we replace/remove the read-only elastic profile usage button with this?
