### ISSUE TITLE
Issues after upgrading to mithril 2.0.3

### ISSUE THREAD

**Issue by GaneshSPatil** [gocd/gocd#6771]
##### Issue Type

- Bug Report

##### Summary

Issues occurred after upgrading to mithril 2.0.3 (#6752)

- [x] A generic error message is shown on users SPA in case of operation failure. [Gauge Spec](https://build.gocd.org/go/files/regression-SPAs-PR/953/Firefox/1/regression-runInstance-6/GaugeReports/reports/html-report/specs/EnableDisableUsers.html)(Fixed as part of #6777)

- [x] Remove webpack patches dir inclusion. Remove [this](https://github.com/gocd/gocd/blob/master/server/webapp/WEB-INF/rails/webpack/config/variables.ts#L37) line. (Fixed as part of #6777)

- [x] Plugin Icon is not rendered for the Elastic agents on the Agents SPA. (Fixed as part of #6792)

- [x] AgentSPA: agent analytics was showing error on click of analytics icon(Fixed as part of  #6813)

- [x] A generic error message is shown on the pipeline config SPA in case of operation failure.  (Fixed as part of #6852)

**Comment by rajiesh** [comment]
Verified on 19.8.0 (9912-33898b3adaf72cedea1604882d3554fd586571a8)
