### ISSUE TITLE
Granular Authorization for different entities such as Environments, Config-Repos, Pipeline Groups etc.  

### ISSUE THREAD

**Issue by adityasood** [gocd/gocd#7222]
### Task Checklist

- [x] Introduce XSLT migration to support defining policy in cruise-config.xml
- [x] Restrict policy definition only for environments.
- [x] Use `view` only policy permissions to grant a user access to environments.
- [x] Bump up roles config API to support policy definition.
- [x] Document Roles config API
- [x] Allow Roles Config SPA to define policy per role.
- [x] Show `Admin` tab with `Environment` Subtab on UI when a user has permission to view the environment.
- [x] Allow users to access environments SPA with read-only permissions to environments.
- [x] Policy evaluation when dealing with multiple roles. See [this](#multiple-roles), [this](https://github.com/gocd/gocd/issues/7222#issuecomment-553301672) and [this](https://github.com/gocd/gocd/issues/7222#issuecomment-553332705)
- [x] Allow policy definition for config repos.
- [x] Document policy tag under [GoCD Configuration Reference](https://docs.gocd.org/current/configuration/configuration_reference.html)
- [x] Document Granular auth feature on [docs.gocd.org](https://docs.gocd.org) similar to [pipeline as code](https://docs.gocd.org/current/advanced_usage/pipelines_as_code.html)
- [ ] (Optional) Write a blog post demonstrating granular auth feature with environments.

### Issue Description

Initial discussions and conversations are documented here: https://github.com/gocd/gocd/issues/4735

**Current Issues:**

Today most of the global entities pipeline_group, template, SCM, package-repo, config-repo, environment, elastic agent profile, artifact store can be configured only by System Admins. In an enterprise setup with multiple teams using the same instance of GoCD, System Admins can have an annoying experience if they have to step in for things like,

1. Creating pipeline_groups
2. Creating environments

**Suggested approach:** Allow auth policies to be defined for roles configured in GoCD.

### Policy to be inlined at a Role level

```xml
<role name="config-repo-admins">
    <policy>
        <allow action="administer" type="configRepo">*</allow>
    </policy>
    <users>
        <user>foo</user>
        <user>bar</user>
    </users>
</role>
```
With the above policy all users belonging to the role config-repo-admins will be able to create, view, edit and delete any ConfigRepo.

```xml
<role name="config-repo-editors">
    <policy>
        <allow action="edit" type="configRepo">*</allow>
    </policy>
    <users>
        <user>foo</user>
        <user>bar</user>
    </users>
</role>
```

With the above policy, all users belonging to the role config-repo-editors will be able to view and edit/update any ConfigRepo.

```xml
<role name="config-repo-viewers">
    <policy>
        <allow action="view" type="configRepo">*</allow>
    </policy>
    <users>
        <user>foo</user>
        <user>bar</user>
    </users>
</role>
```
With the above policy, all users belonging to the role config-repo-viewers will be able to view any ConfigRepo.

#### Who can define these policies?

GoCD System admins can define policies for a Role. Policies will define how the users in the role can access a GoCD entity.

### Types of policy
GoCD will have two types of policy for now -

**Allow**

The policy will allow the access of the current entity based on configured type, action and resource

```
<allow type="environment" action="view">resource_identifier</allow>
```

**Deny**

The policy will deny the access of the current entity based on configured type, action and resource
policy syntax

```
<deny type="environment" action="edit">resource_identifier</deny>
```

||Description |Example|
|--| ----------- | ------- |
| type| The attribute represents the type of GoCD config entity. | wildcard * or pipeline_group, environment, template, agent, etc...
|action|  The attribute represents that what type of action is allowed on the current entity.| wildcard * or Action such as administer, edit, view
|resource_identifier|  A resource name or pattern.| wildcard(* or ?) in it  pipeline_test, environment_prod or a pattern like envrionment_*

* action and type can have a wildcard(\*) but it will not support pattern matching e.g. ref*

**Note: type and action can be extended later on need basis to different entity types.**

** Current Possible actions and there implementation

a.) Administer: This gives CRUD permissions for a resource matching the regex pattern or * matching the entity type

b.) Edit: This allows for Read and update of a resource matching the regex pattern or * of certain entity type

c.) View: This allows for a read of a resource matching the regex pattern or * of a certain entity type.

** Minimum set of permissions to allow to create and edit an environment

Create environment starting with dev_test: Admin permission on the environment for resource identifier dev_* 

```xml
<role name="env_admins">
    <policy>
    <allow action="administer" type="environments">dev_*</allow>
    </policy>
    <users>
        <user>cr_admin1<user>
        <user>cr_admin1<user>
    </users>
</role>
```

** How does system administrator allow administration for two separate teams 

Let us assume there are two teams, Platform Team A and Platform Team B. A GoCD system administrator is asked to create roles Environment Admins for both teams. The roles can be configured as 

```xml
<role name="env_admins_team_A">
    <policy>
    <allow action="administer" type="environments">pt_env_a_*</allow>
    </policy>
    <users>
        <user>suraj<user>
        <user>rahul<user>
    </users>
</role>
```
```xml
<role name="env_admins_team_B">
    <policy>
    <allow action="administer" type="environments">pt_env_a_*</allow>
    </policy>
    <users>
        <user>sulekha<user>
        <user>raj<user>
    </users>
</role>
```

** Assumption: The teams follow a naming convention for environments

**Policy evaluation**

The policy for an entity is denied by default. This would mean the entity would either be only accessible by GoCD system admins (as is the case today) or in some cases like pipeline-group continue to honor existing authorization rules (this may change as we come to implementation of policies for Pipeline Groups).

The policy will be resolved from top to bottom.

```xml
## Example 1
<role name="environment-admins">
    <policy>
        <deny action="view" type="environments">*</deny>
        <allow action="view" type="environments">dev_*</allow> 
    </policy>
    <users>
        <user>foo</user>
    </users>
</role>
```
In the above example users in the role, environment-admins will be denied access to view all environments.

```xml
## Example 2
<role name="environment-admins">
    <policy>
        <allow action="view" type="environments">dev_*</allow>
        <deny action="view" type="environments">*</deny> 
    </policy>
    <users>
        <user>foo</user>
    </users>
</role>
```
In the above example users in the role, environment-admins will be able to view environments matching pattern dev_*.

#### Multiple Roles
**What happens if a user belongs to more than one role?**

For e.g

```xml
<role name="config-repo-admins-01">
    <policy>
        <allow action="view" type="configRepo">*</allow>
    </policy>
    <users>
        <user>foo</user>
        <user>bar</user>
    </users>
</role>
```
```xml
<role name="config-repo-admins-02">
    <policy>
        <deny action="view" type="configRepo">abc_*</allow>
    </policy>
    <users>
        <user>foo</user>
    </users>
</role>
```

For user “foo” what should we consider?

We are currently thinking of a restrictive model wherein in the above example, the user foo will not be able to view any config-repos which match the pattern abc_*

**Comment by GaneshSPatil** [comment]
> What happens if a user belongs to more than one role?

@adityasood -- it depends on how a user has configured role configs and policies.
A user initially might have a blacklist and then want to give specific permissions to a particular user.

Example:
```xml
<pluginRole name="some-team" authConfigId="GitHub">
  <policy>
    <deny action="view" type="environment">*</deny>
  </policy>
  <property>
    <key>Teams</key>
    <value>gocd: committers, reviewers, users</value>
  </property>
</pluginRole>
<role name="bob-the-super-user">
  <policy>
    <allow action="view" type="environment">*</allow>
  </policy>
  <users>
    <user>Bob</user>
  </users>
</role>
```

In the above example, the Administrator does not want to give the environment access to any of the users from `some-team`. But, as `Bob` is a superuser, the Administrator wants to give him the environment access.

As the `Bob` user belongs to both the role-configs and `some-team` says `Deny` access to environments, `Bob` user will not have access to environments.

---

IMO, it should be permissive in case of multiple roles. If one of the roles has allow access, it should allow the user to access the resource.

**Comment by adityasood** [comment]
@GaneshSPatil all users will be denied access by default. here is how I thought about it

1. No user has access to any GoCD entity as all policies are denied by default.
2. If a super admin decides to open up access for some user, they will introduce an `Allow` to allow them access
3. However, if we see an explicit `Deny` policy for an entity for a role user belongs to it takes precedence.

In your example, 

The access to the user `Bob` should be achievable by removing the explicit deny on `some-team`.

Let me know WDYT

**Comment by bjorn-spire** [comment]
This looks great and big 👍 for going for a more restrictive model :)

**Comment by GaneshSPatil** [comment]
Replying to https://github.com/gocd/gocd/issues/7222#issuecomment-553332705

@adityasood --

Yes, Your reasoning makes sense to me! 
To summarize, Policy evaluation would follow a restrictive model in case of a single user belonging to multiple roles which define distinct policies. If one of the defined policies has an explicit deny permission, the user will not be given access to the targeted GoCD entity.

**Comment by GaneshSPatil** [comment]
@adityasood @kritika-singh3 -- should we close this issue as the granular-auth implementation for environments and config-repo has been implemented in GoCD release `v19.11.0` and `v19.12.0` respectively?

We can create separate individual issues for granular auth support for other GoCD entities and link it to this issue.

**Comment by rajiesh** [comment]
Closing this as granular auth implemented for Environment and Config Repository. New issues to be created when add more entities into granular auth
