### ISSUE TITLE
Remove config revisions API

### ISSUE THREAD

**Issue by GaneshSPatil** [gocd/gocd#7340]
Remove  unversioned config revisions API.

The response of the API is as follows:
```cmd
$ curl http://localhost:8153/go/api/config/revisions -u admin:badger
[
  {
    "md5": "365e039a0ed5c53a6cb4584eac0b85e8",
    "time": 1575006156617,
    "schemaVersion": 134,
    "username": "Upgrade",
    "goVersion": "19.11.0 (10610-c7c6a2a5091f6c20e7d631e4dcd0ebc62fa96514)",
    "commitSHA": "b80777d4684da349ff163430035d1bb81e331192"
  },
  {
    "md5": "a0dccd4733a6b13b92f0b5db214c7434",
    "time": 1574936583010,
    "schemaVersion": 134,
    "username": "anonymous",
    "goVersion": "19.11.0 (10610-c7c6a2a5091f6c20e7d631e4dcd0ebc62fa96514)",
    "commitSHA": "2c2995567d69f17e138b427f1cfdcd5ae07d66f7"
  },
  ...
]
```

##### Tasks
- [x] Move API to internal namespace (https://github.com/gocd/gocd/pull/7384)
- [x] Remove API docs (without release announcement) (https://github.com/gocd/api.go.cd/pull/548)
- [x] Remove API after 3 months (~~possibly in `v20.2.0` release~~) (removed as part of https://github.com/gocd/gocd/pull/8102 PR in GoCD release `v20.4.0`)

**Comment by kritika-singh3** [comment]
It is documented API: https://api.gocd.org/current/#list-all-modifications.

Also, if we are removing this, we should also remove the diff API:  https://api.gocd.org/current/#get-repository-modification-diff

**Comment by GaneshSPatil** [comment]
As of now, we've decided to move these API under `internal` namespace as the information exposed by this API is very specific to the internal implementations of how GoCD versions `cruise-config.xml` file.

The URL to access this API has changed from `/go/api/config/revisions` to `/go/api/internal/config/revisions`

\cc: @maheshp @arvindsv @kritika-singh3

**Comment by maheshp** [comment]
Verified on GoCD Version: 20.4.0 (11669-dcb1fc4c5a26445c1091b81acc326d7219a53eed).
