### ISSUE TITLE
Remove all the ids from the instance/history APIs

### ISSUE THREAD

**Issue by kritika-singh3** [gocd/gocd#7360]
##### Issue Type

- Feature enhancement

##### Summary

We need to remove the unnecessary `id` field in the json output of the following APIs as they don't make much sense:

 - [x] Pipeline Instance History (#7215)
 - [x] Stage Instance History (#7279)
 - [x] Job Instance History (#7221)
 - [x] Get Pipeline Instance (#7376)
 - [x] Get Stage Instance (#7379)
 - [x] Get Job Instance (new) (#7221)

**Comment by rajiesh** [comment]
Verified on 20.1.0 release
