### ISSUE TITLE
Placeholder issue for pipeline history SPA

### ISSUE THREAD

**Issue by bdpiparva** [gocd/gocd#7366]
##### Issue Type
- Bug Report

##### Summary

- [x] Pipeline label text size should be increased and should be more pre-dominant, same for the VSM link. #7380
- [x] Hide pagination if there is only one page. #7380
- [x] Show error message on gates when available. #7380
- [x] Triggered by changes. #7380
  - [x] Fonts and size should be the same as what we have on the dashboard. #7380
  - [x] Must have a divider between to modification. #7380 
  - [x] Changes must be listed in grey if they are not responsible for the trigger. #7380
- [x] Pipeline Activity link is coloured, should be black.
- [x] Have we changed the icons for manual trigger and automatic approval
- [x] Allow commenting on pipeline run #7404
  - [x] Move comment API to spark #7389 
  - [x] Document pipeline instance comment API(https://github.com/gocd/api.go.cd/pull/557)
