### ISSUE TITLE
Make create/add button consistent on all SPAs

### ISSUE THREAD

**Issue by GaneshSPatil** [gocd/gocd#7473]
##### Issue Type

- Feature enhancement

##### Summary

GoCD application has a separate page to manage the different GoCD entities. Each page has either an `Add` or `Create` button to create a new entity.
The styles of these add entity buttons are different on each page. Example:
#### On Pipelines Page:
![Screen Shot 2019-12-19 at 11 34 41 AM](https://user-images.githubusercontent.com/15275847/71149162-c15dc780-2253-11ea-812e-fa6a0d56afeb.png)

#### On Environments Page:
![Screen Shot 2019-12-19 at 11 34 50 AM](https://user-images.githubusercontent.com/15275847/71149174-c753a880-2253-11ea-8287-e56e2dd247da.png)

#### On Templates Page:
![Screen Shot 2019-12-19 at 11 34 59 AM](https://user-images.githubusercontent.com/15275847/71149182-cae72f80-2253-11ea-8459-8e31e4be6783.png)

#### On Elastic Agent Configurations Page:
![Screen Shot 2019-12-19 at 11 35 08 AM](https://user-images.githubusercontent.com/15275847/71149187-cd498980-2253-11ea-97a5-7eb8fd7f06d9.png)

##### Expected Results
All GoCD pages should have a consistent `Add` entity button.

##### Actual Results
Different GoCD pages implements the `Add` entity button differently.

##### Possible Fix
We can choose one of the button styles from the above-mentioned 4 button styles.

**Comment by adityasood** [comment]
@GaneshSPatil I think the idea specifically for the new Pipelines SPA is that there are two buttons 
`Create new Pipeline Group` and `Add New Pipeline`. Given the placement of these, @streisguth suggested we keep the primary button in bold and hence `Add New Pipeline` was made bold.

I agree we should standardize on what the text should read and if we need the plus icon. 

Maybe something like `Create <entity-name>`. @streisguth could you help with some thoughts?

**Comment by BElluu** [comment]
Hello. Can I take care of this task?

**Comment by GaneshSPatil** [comment]
Hi @BElluu , Thanks for showing interest in picking up this issue.

Currently, we're in the process of finalizing the **expected result** (_how the create entity button should look on each page_). Depending upon the operations allowed on the page, the styles may differ _slightly_. As mentioned in https://github.com/gocd/gocd/issues/7473#issuecomment-567354046. 

This issue can be picked up once we have a better understanding of the expected result. We'll keep you posted with any further information on this issue.

**Comment by BElluu** [comment]
@GaneshSPatil Thank you so much. Have a peaceful Christmas.

**Comment by GaneshSPatil** [comment]
Hi @gocd/committers,

After having an internal discussion following style has been finalized for the create entity button on the SPAs

![Screen Shot 2020-01-09 at 12 09 49 PM](https://user-images.githubusercontent.com/15275847/72044228-3ebbab80-32d9-11ea-90d2-dda6ccd31009.png)


#### Tasks (Make create/add button consistent on all the following SPAs)

- [ ] Pipelines (`/go/admin/pipelines`)
- [ ] Environments (`/go/admin/environments`)
- [ ] Templates (`/go/admin/templates`)
- [ ] Elastic Agent Configurations (`/go/admin/elastic_agent_configurations`)
- [ ] Config Repositories (`/go/admin/config_repos`)
- [ ] Artifact Stores (`/go/admin/artifact_stores`)
- [ ] Secret Configs (`/go/admin/secret_configs`)
- [ ] Authorization Configurations (`/go/admin/security/auth_configs`)
- [ ] Role Configurations (`/go/admin/security/roles`)

**Comment by GaneshSPatil** [comment]
@BElluu - You can pick up this story. The expected styles for the create entity button and the list of SPAs which require a change has been mentioned https://github.com/gocd/gocd/issues/7473#issuecomment-572416747

Here are some links to get started with GoCD:
1. [Concepts in GoCD](https://docs.gocd.org/current/introduction/concepts_in_go.html)
1. [Setting up GoCD development environment](https://developer.gocd.org/20.1.0/)

Do let us know if you need any assistance to work on this story.

**Comment by BElluu** [comment]
Hi @GaneshSPatil I'm in! :) This is my first time when I'm trying to contribute. How can I assignee to this task?

**Comment by ketan** [comment]
Assigned to @BElluu

**Comment by BElluu** [comment]
Hello!

I have little problem with project on Windows. I installed all requirements for project from https://developer.gocd.org/current/  When I use `gradlew clean prepare` I got that errors:

```
This usually happens because your environment has changed since running `npm install`.
Run `npm rebuild node-sass` to download the binding for your current environment.
    at module.exports (E:\prog\gocd\server\src\main\webapp\WEB-INF\rails\node_modules\node-sass\lib\binding.js:15:13)
    at Object.<anonymous> (E:\prog\gocd\server\src\main\webapp\WEB-INF\rails\node_modules\node-sass\lib\index.js:14:35)
    at Module._compile (E:\prog\gocd\server\src\main\webapp\WEB-INF\rails\node_modules\v8-compile-cache\v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Module.require (internal/modules/cjs/loader.js:848:19)
    at require (E:\prog\gocd\server\src\main\webapp\WEB-INF\rails\node_modules\v8-compile-cache\v8-compile-cache.js:161:20)
    at getDefaultSassImplementation (E:\prog\gocd\server\src\main\webapp\WEB-INF\rails\node_modules\sass-loader\dist\getDefaultSassImplementation.js:24:10)
    at getSassImplementation (E:\prog\gocd\server\src\main\webapp\WEB-INF\rails\node_modules\sass-loader\dist\getSassImplementation.js:19:72)
    at Object.loader (E:\prog\gocd\server\src\main\webapp\WEB-INF\rails\node_modules\sass-loader\dist\index.js:40:61)
 @ ./webpack/views/pages/pipeline_configs/stages/jobs/artifacts.scss 2:26-308
 @ ./webpack/views/pages/pipeline_configs/stages/jobs/artifacts_tab_widget.tsx
 @ ./webpack/views/pages/pipeline_configs/spec/stages/jobs/artifacts_tab_widget_spec.tsx
 @ ./webpack sync spec\.(js|msx|ts|tsx)$
 @ ./spec/webpack/specRoot.js
```

I tried delete node_modules directory and ```use npm install``` and ```npm rebuild node-sass``` but that does not works. 
Below my npm, nodejs and python versions.
![image](https://user-images.githubusercontent.com/11333925/72684627-7cdb7b00-3ae2-11ea-800f-5ca223984436.png)

**Comment by arvindsv** [comment]
I really don't know much about the setup on Windows, but maybe this is relevant? https://stackoverflow.com/a/41454385

**Comment by BElluu** [comment]
> I really don't know much about the setup on Windows, but maybe this is relevant? https://stackoverflow.com/a/41454385

I using Intellij IDEA Community, so I'm not sure that will help but thanks!

**Comment by arvindsv** [comment]
Sorry, thought it was some kind of build tool config you need to do (even though you use IntelliJ). Unfortunately, I don't know anyone who develops on GoCD with Windows. Maybe someone else who sees this can help.

**Comment by BElluu** [comment]
@arvindsv so I need to install Linux next to Windows. I tried work on virtual machine with Linux using VirtualBox, but that works so slow ;/

**Comment by arvindsv** [comment]
@BElluu Yes, working on VirtualBox will be quite slow. I don't know what the state of Docker on Windows is currently, but I know @tomzo used to use https://github.com/kudulab/docker-gocd-dojo to build GoCD. Not sure it'll work for you on Windows. If not, Linux it is. :)

**Comment by BElluu** [comment]
@arvindsv I tested that on Linux but was too slow. I can't use Docker for Windows because I have Home Edition :( nvm, I need to install Linux next to Windows. I will buy flash drive tomorrow, because I can't find my old :)

**Comment by ketan** [comment]
[This file](https://github.com/gocd-contrib/gocd-oss-cookbooks/blob/master/provision/install-packages.ps1) lists the specific packages and versions that you would need in order to build/compile gocd. You might be missing the compiler so try [this line](https://github.com/gocd-contrib/gocd-oss-cookbooks/blob/master/provision/install-packages.ps1#L37) before installing other packages.

**Comment by BElluu** [comment]
I installed Linux and coz of COVID I have some time soso I try do this task in next days:)
