### ISSUE TITLE
Placeholder issue for granular auth on elastic profiles

### ISSUE THREAD

**Issue by rajiesh** [gocd/gocd#7649]
##### Issue Type

- Bug Report

##### Summary

Placeholder issue for granular auth on elastic profiles

- [x] Roles configured with policy to administer elastic profile unable to perform any CRUD operations since API returns 403. More details on this [comment](https://github.com/gocd/gocd/issues/7649#issuecomment-576637695)
- [x] Roles configured with policy to view elastic profile not allowed to perform clone or view usage report. More details on this [comment](https://github.com/gocd/gocd/issues/7649#issuecomment-576640311)
- [x] User not allowed to add elastic profile if the role policy allows view on some elastic profile and administer on. More details on this [comment](https://github.com/gocd/gocd/issues/7649#issuecomment-576640311)
- [x] UI error message alignment issue when error on resources. More details on this [comment](https://github.com/gocd/gocd/issues/7649#issuecomment-576640612)

**Comment by rajiesh** [comment]
Create a role with policy as,

```
<role name="prod">
          <users>
            <user>prod_user</user>
          </users>
          <policy>
            <allow action="administer" type="elastic_agent_profile">team1:prod</allow>
          </policy>
        </role>
```

Now when `prod_user` access the elastic agent profiles page all crud operations for `prod` elastic profile is enabled, but any action returns 403 as response

**Comment by rajiesh** [comment]
Create a role with policy as,

```
<role name="test">
      <users>
            <user>test_user</user>
      </users>
      <policy>
            <allow action="view" type="elastic_agent_profile">team1:prod</allow>
            <allow action="administer" type="elastic_agent_profile">team1:test</allow>
       </policy>
 </role>
```

With this configuration 2 issues can be observed,

* The `test_user` cannot clone or view usage info of `team1:test` elastic profile since api endpoint `/api/elastic/profiles/test` returns 403
* The `test_user` cannot create any new elastic profile in cluster `team1` even when the policy says `administer` for elastic profile with name `test`

**Comment by rajiesh** [comment]
UI alignment issue when there is error on resources

<img width="1009" alt="Screen Shot 2020-01-21 at 4 45 06 PM" src="https://user-images.githubusercontent.com/6533924/72801345-4f700800-3c6f-11ea-9f42-fed18e14f80c.png">

**Comment by rajiesh** [comment]
Verified on 20.1.0 (11090-752c45e6489aa30ef3a1fd911c82f97eb8104eaf)
