### ISSUE TITLE
Dashboard Enhancement (Part II)

### ISSUE THREAD

**Issue by GaneshSPatil** [gocd/gocd#7687]
##### Issue Type

- Feature enhancement

##### Summary

Improve GoCD dashboard to add following new functionality:
- [ ] Expand Collapse Pipeline Groups/Environments
- [ ] Reorder Pipeline Groups. (https://github.com/gocd/gocd/issues/7687#issuecomment-580658386)
- [ ] Reorder Pipelines within a pipeline group. (https://github.com/gocd/gocd/issues/7687#issuecomment-580658386)
- [ ] Manual stage trigger from dashboard. (https://github.com/gocd/gocd/issues/7687#issuecomment-580652610)
- [ ] Rerun/Cancel a stage from dashboard. 
- [ ] Errors and Warning on Pipelines.
- [ ] Go to Job Details Page from Dashboard. (https://github.com/gocd/gocd/issues/3965#issuecomment-580663387)

Related issues: #3965 #3889 #3882 #3704

**Comment by GaneshSPatil** [comment]
#### Manual stage trigger from dashboard

![Screen Shot 2020-01-31 at 2 44 24 PM](https://user-images.githubusercontent.com/15275847/73527287-cf992900-4438-11ea-810e-6cf05131ccf7.png)

**Comment by GaneshSPatil** [comment]
### Reorder Pipelines and Pipeline Groups on Dashboard.

Currently, Pipelines are sorted on the dashboard based on the config.xml order. See `display_order_weight`  for ordering pipelines from config repository (https://github.com/gocd/gocd/issues/6042 and https://github.com/gocd/gocd/issues/3704).

Whereas, sorting the pipelines and pipeline groups based on the cruise-config.xml order might not be ideal for all the users.
_Example_: the pipelines that a system-administrators wants to see vs the pipelines a particular team wants to see.

Hence, **Use User Personalization to store Pipeline and Pipeline Group/Environment sort order**

Each user can define their own sort order (for each personalized view).
As the user personalization view contains all the required information about pipelines, pipeline groups and environments, it would be easier to add the entity sort order ability.

@gocd/committers  -- Thoughts??

**Comment by arvindsv** [comment]
Need to consider what happens when new pipelines come in, etc. but it is similar to how it is now when showing and hiding pipelines, I suppose.

**Comment by kritika-singh3** [comment]
Can we also consider this: https://github.com/gocd/gocd/issues/6246
