### ISSUE TITLE
[Breaking Changes] GoCD Plugin Changes with respect to Pipeline Config SPA

### ISSUE THREAD

**Issue by GaneshSPatil** [gocd/gocd#7801]
In order to make the UI/UX consistent across all pages of GoCD, GoCD is rebuilding the Pipeline Config Edit Page (changing into a Single Page App).

As part of this page rewrite, following changes needs to be done on the plugins:
### Task Plugins View:
GoCD Task Plugins implements [Get Task View](https://plugin-api.gocd.org/current/tasks/#task-view) extension call, which returns a task form.
As part of this HTML view, plugin authors may have used `classnames` for the HTML elements that conflicts with the GoCD `classnames` causing GoCD styles to be applied to the plugin view.

**Going forward, the plugin view will be rendered in a sandbox, causing GoCD styles not to be applied on the provided form**. Hence, plugin-authors are expected to fix the [Get Task View](https://plugin-api.gocd.org/current/tasks/#task-view)  plugin API call to return the HTML view along with the required styles. 

List of plugins that requires a fix:
  - [ ] [XUnit Converter](https://github.com/gocd-contrib/xunit-converter-task)
  - [ ] [Powershell Task](https://github.com/manojlds/gocd-powershell-runner/blob/master/README.md)
  - [ ] [RapidDeploy Package Builder](https://github.com/MidVision/go-rapiddeploy/wiki#rapiddeploy-package-repository-plugin)
  - [ ] [RapidDeploy Job Runner](https://github.com/MidVision/go-rapiddeploy/wiki#rapiddeploy-job-runner-task-plugin)
  - [ ] [Groovy Task Plugin](https://github.com/4finance/go-plugin-groovy)
  - [ ] [Maven Task Plugin](https://github.com/ruckc/gocd-maven-plugin)
  - [ ] [Script Executor Task Plugin](https://github.com/gocd-contrib/script-executor-task)
  - [ ] [Publish to S3](http://oss.indix.com/gocd-s3-artifacts/publish.html)
  - [ ] [Fetch from S3](http://oss.indix.com/gocd-s3-artifacts/fetch.html)
  - [ ] [Docker task](https://github.com/manojlds/gocd-docker)
  - [ ] [Publish to Artifactory](https://github.com/tusharm/go-artifactory-plugin)
  - [ ] [MSBuild Task](https://github.com/akanyer/gocd-msbuild-taskplugin/blob/master/README.md)
  - [ ] [Apache Brooklyn Task](https://github.com/rjgarciap/ApacheBrooklyn-Task-Plugin/blob/master/README.md)
  - [ ] [Deploy to AWS OpsWorks](https://github.com/tispr/gocd-opsworks-plugin)
  - [ ] [Gradle Task plugin](https://github.com/jmnarloch/gocd-gradle-plugin)
  - [ ] [Health Check Task plugin](https://github.com/jmnarloch/gocd-health-check-plugin)
  - [ ] [SBT Task plugin](https://github.com/jmnarloch/gocd-sbt-plugin)
  - [ ] [Nessus Scan Task plugin](https://github.com/Haufe-Lexware/gocd-plugins/wiki/Nessus-Scan-Task-Plugin)
  - [ ] [SonarQube Quality Gate Task plugin](https://github.com/Haufe-Lexware/gocd-plugins/wiki/SonarQube-Quality-Gates-Task-Plugin)
  - [ ] [Check_MK monitoring plugin](https://github.com/Haufe-Lexware/gocd-plugins/wiki/Check_Mk-Monitoring-Task-Plugin)
  - [ ] [Slack Task plugin](https://github.com/Vincit/gocd-slack-task)
  - [ ] [Docker pipeline plugin](https://github.com/Haufe-Lexware/gocd-plugins/wiki/Docker-plugin)
  - [ ] [Scalastyle Github Pull Request plugin](https://github.com/insano10/gocd-pr-comment-scalastyle)
  - [ ] [Artifactory Plugin](https://github.com/eaiesb/Gocd-Artifactory-Plugin)
  - [ ] [Diawi Uploader Plugin](https://github.com/ReviakinAleksey/diawi-upload-plugin)
  - [ ] [Docker Exec Plugin](https://github.com/cma-arnold/gocd-docker-exec-plugin)
  - [ ] [Backblaze B2 Publish Task Plugin](https://github.com/kszatan/gocd-b2-artifacts)
  - [ ] [Backblaze B2 Fetch Task Plugin](https://github.com/kszatan/gocd-b2-artifacts)
  - [ ] [Dunner - Docker Task Runner Plugin](https://github.com/leopardslab/dunner-gocd-plugin)
### Task Plugins required field validations:
GoCD Task Plugins provides field metadata as part of [Get Task Configuration](https://plugin-api.gocd.org/current/tasks/#task-configuration) extension call, which returns metadata about all the fields.
If a plugin marks any of the fields as required field, GoCD used to perform required field validation during a config save or update operation (performed from UI).

As the plugin configuration fields can contain following complexities:
- Configurations updated from disk or full config save.
- Field dependent validations. Example: If the X checkbox is selected validate Y value is specified.

Hence, GoCD will not perform required field validations for task plugins, and task plugins are expected to perform these validations during [Validate Configuration](https://plugin-api.gocd.org/current/tasks/#validate-configuration) extension call.

List of plugins that requires a fix:
  - [ ] [XUnit Converter](https://github.com/gocd-contrib/xunit-converter-task)
  - [ ] [Powershell Task](https://github.com/manojlds/gocd-powershell-runner/blob/master/README.md)
  - [ ] [RapidDeploy Package Builder](https://github.com/MidVision/go-rapiddeploy/wiki#rapiddeploy-package-repository-plugin)
  - [ ] [RapidDeploy Job Runner](https://github.com/MidVision/go-rapiddeploy/wiki#rapiddeploy-job-runner-task-plugin)
  - [ ] [Groovy Task Plugin](https://github.com/4finance/go-plugin-groovy)
  - [ ] [Maven Task Plugin](https://github.com/ruckc/gocd-maven-plugin)
  - [ ] [Script Executor Task Plugin](https://github.com/gocd-contrib/script-executor-task)
  - [ ] [Publish to S3](http://oss.indix.com/gocd-s3-artifacts/publish.html)
  - [ ] [Fetch from S3](http://oss.indix.com/gocd-s3-artifacts/fetch.html)
  - [ ] [Docker task](https://github.com/manojlds/gocd-docker)
  - [ ] [Publish to Artifactory](https://github.com/tusharm/go-artifactory-plugin)
  - [ ] [MSBuild Task](https://github.com/akanyer/gocd-msbuild-taskplugin/blob/master/README.md)
  - [ ] [Apache Brooklyn Task](https://github.com/rjgarciap/ApacheBrooklyn-Task-Plugin/blob/master/README.md)
  - [ ] [Deploy to AWS OpsWorks](https://github.com/tispr/gocd-opsworks-plugin)
  - [ ] [Gradle Task plugin](https://github.com/jmnarloch/gocd-gradle-plugin)
  - [ ] [Health Check Task plugin](https://github.com/jmnarloch/gocd-health-check-plugin)
  - [ ] [SBT Task plugin](https://github.com/jmnarloch/gocd-sbt-plugin)
  - [ ] [Nessus Scan Task plugin](https://github.com/Haufe-Lexware/gocd-plugins/wiki/Nessus-Scan-Task-Plugin)
  - [ ] [SonarQube Quality Gate Task plugin](https://github.com/Haufe-Lexware/gocd-plugins/wiki/SonarQube-Quality-Gates-Task-Plugin)
  - [ ] [Check_MK monitoring plugin](https://github.com/Haufe-Lexware/gocd-plugins/wiki/Check_Mk-Monitoring-Task-Plugin)
  - [ ] [Slack Task plugin](https://github.com/Vincit/gocd-slack-task)
  - [ ] [Docker pipeline plugin](https://github.com/Haufe-Lexware/gocd-plugins/wiki/Docker-plugin)
  - [ ] [Scalastyle Github Pull Request plugin](https://github.com/insano10/gocd-pr-comment-scalastyle)
  - [ ] [Artifactory Plugin](https://github.com/eaiesb/Gocd-Artifactory-Plugin)
  - [ ] [Diawi Uploader Plugin](https://github.com/ReviakinAleksey/diawi-upload-plugin)
  - [ ] [Docker Exec Plugin](https://github.com/cma-arnold/gocd-docker-exec-plugin)
  - [ ] [Backblaze B2 Publish Task Plugin](https://github.com/kszatan/gocd-b2-artifacts)
  - [ ] [Backblaze B2 Fetch Task Plugin](https://github.com/kszatan/gocd-b2-artifacts)
  - [ ] [Dunner - Docker Task Runner Plugin](https://github.com/leopardslab/dunner-gocd-plugin)

**Comment by GaneshSPatil** [comment]
The old rails based pipeline config edit page has been removed as part of GoCD Release v20.5.0. 
The plugins mentioned as part of the [issue comment](https://github.com/gocd/gocd/issues/7801#issue-573907597) might not work appropriately on the new mithril based Pipeline Config SPA and such plugins may require a fix.

If the users or the plugins authors come across this issue, they're urged to create a separate issue on the individual plugin's repository.

Closing...
