### ISSUE TITLE
Remove GoCD Data Sharing

### ISSUE THREAD

**Issue by GaneshSPatil** [gocd/gocd#8271]
## Tasks

- [x] Remove data sharing SPA.

- [x] Remove data sharing related APIs:
	- [x] Data Sharing Settings API
	- [x] Data Sharing Notification Auth API
	- [x] Usage Data API (Plain)
	- [x] Usage Data API (Encrypted)
	- [x] Data Reporting Info API
	- [x] Data Reporting Start API
	- [x] Data Reporting Complete API

- [x] Cleanup DataSharingSettings and UsageStatisticsReporting tables on an upgrade.

- [x] Remove javascript code which actually reports the data.

- [x] Remove data sharing from the admin dropdown list

- [x] Remove notification about data sharing.

- [x] Remove code which stores data sharing settings into database.

- [x] Remove Data Sharing Certificate from GoCD Core.

- [x] Do not report usage data related server id for the version check

- [x] Remove functional specs

- [ ] Take latest backup of the data sharing postgres database and upload it to s3 (glacier).

- [ ] Remove data sharing cloud formation stack.

- [x] Achieve usage-data-collector-app repository from gocd-private on GitHub.

- [x] Remove API documentation

- [x] Verify last 12 releases of GoCD continue to work when data sharing lambda is removed. (when datasharing.gocd.org is down)

- [ ] Remove usage data related pipelines from build.gocd.org

**Comment by kritika-singh3** [comment]
Verified as per [comment](https://github.com/gocd/gocd/pull/8278#issuecomment-659309187)
