### ISSUE TITLE
Add page to display all materials used in GoCD

### ISSUE THREAD

**Issue by kritika-singh3** [gocd/gocd#8331]
#### Issue Type

- Feature proposal

Parent Issue: #1105, #1145, #1545

### Summary

Propose a materials SPA accessible to all users containing a brief about the materials used in GoCD

### Details

The SPA will be visible to all users. The SPA will

 - display the list of unique materials visible to the current user
 - show the latest commit for each material as available in GoCD
 - has an option to list the modifications i.e. commits available for each material
 - for each of the modifications - display a link to its VSM.

Good to have feature for this SPA:

 - if `auto_update` is set to `false` for non-dependency materials - show an option to trigger an MDU
 - also display the current material's update - whether is in progress or not (similar to config-repo)
 - has an option to list all the pipelines which uses this material

### Challenges or TODO

 - No MDU trigger API support for TFS, Perforce and Package materials
 - Add an API which reports whether an MDU is in progress for a given fingerprint

### Questions

 - Should the materials be grouped by their type, i.e., git, mercurial, etc?
 - Material fingerprint - in the header or body?
 - There will no delete icon but should we provide a link to materials tab instead?
 - While displaying modifications - should we also display modified files?

Thoughts and suggestions are welcomed!

#### Suggested UI

![IMG_20200709_133003](https://user-images.githubusercontent.com/41165891/87013930-07c34580-c1e9-11ea-8b72-34118991707d.jpg)

![IMG_20200709_133028](https://user-images.githubusercontent.com/41165891/87014115-448f3c80-c1e9-11ea-9459-aba3bcf6d0d1.jpg)

**Comment by maheshp** [comment]
@kritika-singh3 listing out the things we discussed,

Materials Page

1. List all unique materials(This list view would be very similar to the Config Repo SPA) 
   What should the list show?
     - Material name
     - Material attributes e.g url/branch
     - latest commit revision
     - latest commit message
     - latest commit author
     - Indicate if auto_update is enabled or not
     - Icon for material type

2. Search for a material by name/url within the page
   - Serach materials by type/branch?

3. Actions(Buttons) on the list
   - Trigger MDU
   - View VSM for the latest commit
   - A edit button which redirects to materials page on pipelines, scm or package material (What happens when a material is associated with multiple pipelines)

4. Details
   - List pipelines which are dependent on the material
   - List last 5 modifications
   - Option to saerch for a modification based on revision

5. Permissions
   - Should not show all materials, show materials with view permission

6. Errors & Warnings
 - Show errors for a material

7. MDU status
- On triggering an MDU show the status of the material update.

**Comment by kritika-singh3** [comment]
Few open questions:
 1. Should we showcase Pluggable SCM and Package attributes for the material of the kind or just a link to the respective SPAs would work.
2. The edit material action button for Pluggable SCM and Package material would link to the edit modal of the respective kind. What about the inline materials i.e. git, mercurial, perforce, tfs and subversion
3. The modification search feature - should it be an exact match on revision or a pattern match on all the attributes of a modification.
4. Should we showcase all the results from the search or just top 5 or allow pagination.

**Comment by maheshp** [comment]
@kritika-singh3 my initial thoughts,

> Should we showcase Pluggable SCM and Package attributes for the material of the kind or just a link to the respective SPAs would work.

Showing the attributes for all material types might be useful, but I would start with just showing the information that might be useful for users to identify a material on this page. For builtin materials show `Material Name`, `URL\Branch` and for Pluggable and Package Materials `Name`.

> The edit material action button for Pluggable SCM and Package material would link to the edit modal of the respective kind. What about the inline materials i.e. git, mercurial, perforce, tfs and subversion

Do you think it would be ok to show the edit button only for the Pluggable and Package materials. I am thinking we should have link to show usages of this material. On clicking the Usages icon we should list all the pipelines which use this material in a modal and also provide a link to edit the pipelines.

>The modification search feature - should it be an exact match on revision or a pattern match on all the attributes of a modification.
Should we showcase all the results from the search or just top 5 or allow pagination.

Does it makes sense to have a link to see all the changes. Clicking the changes link should open a modal with all the recent modifications with a link to VSM against each of them. We can have cursor based pagination for this page to view more/less modifications.
This modal can also have an option to search for modification based on the revision to start of.

WDYT?

**Comment by kritika-singh3** [comment]
Update: The Materials SPA has been introduced behind a toggle `show_materials_spa` which is by default, `false`.

#### Completed 
1. List all unique materials: name, major attributes (url, branch/domain) - grouped by `type`
    - List the latest modification with a link to the VSM
    - Added an icon based on material type
    - Only the materials belonging to the pipeline for which the current user has view permissions are shown
2. Added support for page-level search based on materials config (type, name and description i.e. url/branch/domain) and latest modification (revision, comment and username)
3. List pipelines which are uses the corresponding material which links to the materials tab of the edit pipeline config page

#### In Progress
1. Add an edit button for package and plugin materials which will open the corresponding modal on a separate tab (#8436)
2. List modifications related to a materials with corresponding VSM link: currently latest 10 modifications are shown. Cursor based pagination has been implemented to view the older ones. (#8436)
3. Allow user to search for a modification based on revision, comment and username (#8436)

#### Todo

- [ ] Show MDU status for a given material - this would mean the current internal API has to be updated to contain this info. The SPA would need to implement a poller for this. Also `etag` needs to be added to prevent excessive re-rendering.
 - [ ] Show the value of `auto_update` for a material. How about a refresh icon near the Material type?
 - [ ] Add button to trigger MDU for a material. Should this button be shown for materials with `auto_update` set to `false`?
 - [ ] Showcase errors and warnings (if any) for a given material
 
cc:\ @gocd/committers

**Comment by kritika-singh3** [comment]
Update: All the features initially discussed have been implemented. There are few queries which still needs to be decided:
1. Ability to link a material from materials tab of pipeline config to the one on Materials SPA: Take a scenario of failing MDU or MDU stuck. The error will be showcased in server health messages along with the affected pipelines. The user would visit the materials tab. From there he/she should have a link to go the materials tab which might have more details on this error.
2. Currently the icon to view all the modifications is a list one. Should we showcase different icons/word for each material type (git, hg, tfs). If we do agree on this, this should not give an impression that we treat them differently. For GoCD, all commit/revision are modifications.
3. Add an ability to edit all the occurrences of a material config: Currently only package and plugin materials have an edit icon which redirects to the edit on the respective SPA. Should we give a feature which enables user to edit all the occurrences of an inline material at a single place. Scenario: credential rotation, change of url. Thing to take care: the user might have view permission but not operate.
4. Also what would be the best way to represent that a material is polled or not (auto_update value)

**Comment by kritika-singh3** [comment]
The SPA is all done and released as a part of GoCD 20.8.0 release.
