### ISSUE TITLE
Migrate GoCD Helm Chart to GoCD hosted repository

### ISSUE THREAD

**Issue by GaneshSPatil** [gocd/gocd#8545]
##### Tasks

- [x] Migrate GoCD helm chart from [helm/charts](https://github.com/helm/charts) to [gocd/helm-chart](https://github.com/gocd/helm-chart) Github repository.
	- [x] Copy over all the releases.
	- [x] Copy over all the code.

- [x] Setup a helm chart repository for gocd/helm-chart](https://github.com/gocd/helm-chart) (using github pages).

- [x] Setup CI using Github Actions:
	- [x] Lint
	- [x] Install

- [x] Setup Release Github Action. (This action is responsible for updating index.yaml and drafting a new release whenever app version is changed.)

- [x] Update Documentation to mention only helm v3 installation steps.

- [ ] ~~Remove chart testing (See gocd/templates/tests/gocd-test.yaml), as the tests only verifies the app is accessible. (The same verification has been performed (in a better way) by CI github action).~~

- [x] Setup GoCD Pipeline to update app version whenever a new release of GoCD is pushed.

- [x] List the new GoCD hosted Helm chart on [Helm Hub](https://hub.helm.sh).

- [x] Deprecate the existing GoCD Helm Chart from [helm/charts](https://github.com/helm/charts) providing new chart information.

- [x] Maybe delete (or archieve) https://github.com/gocd/gocd-helm-chart repo as we've our own hosted helm chart.

- [ ] [Scheduled for November] Delete pipeline which updated gocd helm chart on helm/chart repos as the chart has been deprecated.

- [x] Update www.gocd.org/download page to use the new gocd helm chart repository.
