### ISSUE TITLE
Moving GoCD CLA App Mongo DB from Heroku Mlab to MongoDB Atlas

### ISSUE THREAD

**Issue by GaneshSPatil** [gocd/gocd#8616]
#### Why?

MongoDB Mlab (addon) is now part of MongoDB, Inc itself. See [this](https://docs.mlab.com/mlab-to-atlas/) announcement for more information.
As part of this merging, the MongoDB mlab addon from heroku is depreacated and will be removed on 10th November, 2020.

#### Tasks

- [X] Migrate the mlab databse to Mongodb Atlas.
  - [X] This database has been created under [THOUGHTWORKS STUDIOS GOCD](https://cloud.mongodb.com/v2#/org/5ead908cc42d6d5c93914208/projects) organization under @GaneshSPatil account.
  - [X]	Add @maheshp @kritika-singh3 and @marques-work as organization adminstrators.
  
- [X] Update new database url on 1password (See `Cla App` Secure note)
	- [X] Keep the old heroku url with label `MongoDbUrlFromHeroku` under the same secure note.

- [X] Update the new url on `mini-apps` CloudFormation stack.

- [X] Update `backup-aws` pipeline to backup the database from MongoDb Atlas.
	- [X] Added scripts to backup mongodb atlas under gocd-private/backups repository (and added a GoCD job for the same).
	- [X] Push the MongoDB Atlas backup to the same s3 bucket, inside a different folder (named `MongoDBAtlas`).

#### To be done post verification:

- [x] Delete older database from MongoDB Mlab addon (@GaneshSPatil @maheshp has access to do this).
- [x] Delete job which backs up the older mongodb mlab database from GoCD `backup-aws` pipeline.
- [ ] Delete older backups from s3.

**Comment by maheshp** [comment]
S3 cleanup is pending.
